myfaq=[
  "Contracts:",
  ["How do these contracts make theft and fraud almost impossible?",
  "Because both individuals or parties will often have more invested in the contracts than they stand to gain by cheating it. The contracts operate on a 'win-win' or 'lose-lose' philosophy. If one party attempts theft or breaches the contract the other may refuse to release the funds. The funds are then destroyed when the time limit expires. A liar would not even bother to use a service like this. This is the solution to stop deception once and for all. This is decentralized honesty.",
  "What happens if a user is not available?",
  "It is strongly recommended that users assign cosigners in settings such as a relative, friend or spouse in case they become unavailable. Also they should provide their contact information and stay in close contact with the counter-party.",
  "What types of contracts can users create?",
  "This system works for any type of contracts a user can fathom such as sales of goods, services, commodities, bartering, over the counter deals, employment, games, real estate and long term contracts. There is endless opportunities especially in international deals where there is no common agreement on law. Actually these contracts would even work in an anarchy and force honesty in the process.",
  "How is shipping handled?",
  "Users should sign up for a corporate shipping account to save money and then let users counter-offer them when the shipping is outside of what has been calculated. Alternatively they may also bill for shipping within escrow through a separate contract or a payment within escrow. Just make sure the deposits cover the payment.",
  "What if someone does not have enough for the deposit?",
  "It is always strongly recommended both users deposit. However sometimes a new user will sell their first item using a guarantor or cosigner to ensure they proceed with the deal. They would still need some coins to cover gas fees."],
  "Markets:",
  ["Are these markets truly decentralized?",
    "There is no owner or company that controls this system. Deals are posted on the blockchain and the details are linked using a torrent. Open contracts can be searched using their 'hash tags'. It is not possible to censor these markets as the core ideology of decentralization is freedom and fairness.",
    "Are the markets free? How can users make money using this?",
    "There is no company to collect fees so the markets in theory are free. However an affiliate fee from 0-1% may be deducted from completed deals payable to the affiliate that the buyer brings. This is similar to traditional markets where users pay people to advertise their products. Users who become affiliates can use the markets for free and get discounts by making themselves their own affiliate. Users can profit by marketing products or services using their affiliate link.",
    "How can someone become an affiliate?",
    "Users become an affiliate by using the markets. They only need to make sure the deals they do pay above the minimum threshold and that they do enough deals to qualify. There may be a 'cool down' between deals to guarantee they are not bots. Once an affiliate is assigned to someone's account the affiliate profits off of every deal they do. A user can choose to change their affiliate at any time. An affiliate that is assigned to a specific deal is locked into the deal to profit if it completes. Cancelled deals do not have to pay any affiliate. To avoid conflict of interest, the buyers affiliate is the one who gets the fees.",
    "Are users forced to choose an affiliate?",
    "If a user does not choose an affiliate they may pay a very small penalty and the affiliate fee is burned. The burning of the fee guarantees that the markets are ownerless and that users are the ones who get to choose. If a user visits an affiliate link and they already have an affiliate assigned, the user will pay the affiliate at the link. The system attempts to be as fair as possible.",
    "How can ownerless markets be moderated?",
    "It is strongly believed that users should self moderate. This can be done using artificial intelligence which can read offers that are posted and can let users filter them based on some criteria. This ensures the responsibility falls on the users themselves and dramatically reduces costs while increasing the safety of the markets. Actually we believe this is the perfect architecture for an internet that protects free speech while also letting users choose what they decide is false instead of having others choose for them.",
    "Who is responsible for what users post?",
    "Currently social media platforms are not responsible for users posts. These markets are free so no company profits from the programs use. Affiliate fees are only paid to whoever the user chooses. Knife manufacturers are not responsible for the misuse of their products as that would be unfair. Therefore, users are entirely responsible for what they post.",
    "Who performs the 'know your customer' process?",
    "Some users may perform contracts that require them to know who they are dealing with. Not all countries require this while others do. Since there is no third party, users must perform this themselves with the parties they transact with.",
    "How can artificial intelligence be included in the current site design?",
    "The markets are still growing so for now it is not filled with any spam. Eventually it may be asked that users supply an API key for an artificial intelligence robot when offers are posted to the open markets. This also helps them filter spam based on their own settings.",
    "What currencies can I deposit to the markets?",
    "The contract accepts almost all currencies in theory. However the user interface may only show the standard currencies such as Ethereum or DAI. Coin communities interested in being a part of this can submit a request to the website. Coins are typically considered based on their decentralization and unique code.",
    "How do I contact support?",
    "This website is hosted for free online and it is a community driven project. Therefore there is no official support channel aside from the community of users itself. The users earn all the profits, and their associated affiliates. Therefore, they determine the success of the project. Therefore, support should be obtained by joining the community on social media."],
  "Disputes:",
  ["Is there arbitration options?",
    "There is no third party to these contracts and that is what makes the system truly perfect. Third parties have no knowledge of who is telling the truth and that only creates opportunities for liars to profit off of abuse. Arbitration also increases the cost of doing business and it is not necessary for a successful deal. Nonetheless, a user may assign a cosigner who can act as an arbiter in case of dispute.",
    "Is it fair to for both parties to lose during a dispute?",
    "Yes and for many great reasons. The most important one is simply because the users agree to the terms by using this system and most people would gladly pay extra to punish a thief by instantly making them lose funds. Court systems do not know the truth and often cause victims to lose even more money. When both parties lose it teaches a strong lesson to liars that they can never deceive a double deposit escrow. Also, the amount users save by not having to pay third parties is made back within a few deals.",
    "Why are funds on failed contracts burned? Why can't those funds be given to charity?",
    "To give lost funds to charity would only create a conflict of interest as the charity could conspire to destroy contracts. It's possible when the whole world starts using this system that insurance companies could assist in cases with overwhelming evidence in favor of an impacted party.",  
    "Are there variations on dispute resolution that work with two party escrow?",
    "Users could have multiple signatures or members for each party. Also variations on the escrows may be possible such as how defaults are handled, using mixed funding options, time locks and so forth.",
    "What if a person tries to blow up contracts deliberately to harm the site?",
    "The software has a reputation system so the first time they try this it's shown that they have a failed contract. Users would require a much higher deposit from a user who does this especially if it's frequent. A user who does this will eventually lose all their money and this is how society should be. The wealthy people should be the honest ones. Currently it seems dishonest people are usually the wealthy ones and this software is the first step to changing that.",
    "What should users do to avoid a dispute?",
    "They should start by giving a lot of time for a deal to complete. We recommend at least a month even if the deal can clear in a day. When sending packages they should buy insurance. Users should make sure they have cosigners and share a way to contact them. If users are completely unreliable they should seek to cancel the deal by mutual consent.",
    "Who is liable if a contract can’t be completed due to counterparty failure?",
    "You and your counterparty are the only ones liable. This is an innovative solution to preventing fraud. There is no third party to protect you in the case of a failed contract. But that also means there are no excessive fees to transact and very strong incentive for parties to work together. You can adjust deposits for unknown parties to whatever levels you deem necessary to ensure success."],
  "Security and privacy:",
  ["Are deals encrypted by default?",
    "For encryption to be activated both users must publish their encryption data. It is not necessary to encrypt open offers to the markets as they are known to anyone with access to the software. However private offers are encrypted when both users publish their public keys.",
    "Does this website collect any data on users?",
    "No it does not. The only data that can be seen is what you choose to publish publicly to the blockchain.",
    "What happens if I forget my password or lose my account?",
    "There is no account recovery. So please be sure you are able to back up any relevant keys or passwords. The security advantage to blockchain is that your funds are perfectly safe and never shared with anyone.",
    "Is this code open source?",
    "All of the code is completely free and open source under the 'Coinleft Public License for BitBay'. The code has also been audited multiple times and those reports are published on Github. Users and companies should continue to audit it proving it's safety.",
    "What is the safest way to access this site?",
    "The most secure way to access this page is to download it's source code from Github and run it locally. This way nobody on earth can change the code as you have a hard copy.",
    "When should users automatically accept offers?",
    "The feature to automatically accept valid offers is recommended only for advanced users for specific types of contracts. It is more common to first understand the person you are doing business with than to accept anyone who matches your offer. Also only users who check the markets frequently should allow this or else they risk having the offer on the markets unsupervised.",
    "Are there any tips for backups and remembering a password?",
    "One clever way to choose a unique password is to choose some words from a specific chapter of a book you like. Then replace one of the letters with a number. 'Salt' the password by choosing different uncommon chapters or books and combining them. Then you only need to remember what you picked. For backup you can write your choices down on paper. You can store it on multiple devices. You should never store passwords online as someone else might see it.",
    "Is it safer to use Metamask or login using a password?",
    "Logging in with a password is the safest because it doesn't rely on a 'browser extension' that could be maliciously updated without the user understanding the changes. However it is strongly recommended you use an open source browser such as Chromium, Thorium or Firefox. Mandatory browser updates should be disabled and the browser should be run without any extensions on a clean open source operating system such as Linux."]
]