var langOptions = ['Arabic','Chinese','English','French','German','Italian','Japanese','Korean','Portuguese','Russian','Spanish'];
var languages={}
languages['ar']={
  "1": {"#ar": "أسواق بيت باي اللامركزية"},
  "2": {"#ar": "أسواق بيت باي اللامركزية"},
  "3": {"#ar": "اتصل بـ ميتاماسك"},
  "4": {"#ar": "غير متصل"},
  "5": {"#ar": "الأسواق"},
  "6": {"#ar": "العروض"},
  "7": {"#ar": "العقود"},
  "8": {"#ar": "الحساب"},
  "9": {"#ar": "حول"},
  "10": {"#ar": "السلع"},
  "11": {"#ar": "الخدمات"},
  "12": {"#ar": "التبادل"},
  "13": {"#ar": "تداول نقطي إلى نقطي"},
  "14": {"#ar": "السلع"},
  "15": {"#ar": "الأسواق"},
  "16": {"#ar": "إنشاء عقد/عرض"},
  "17": {"#ar": "البحث"},
  "18": {"#ar": "السابق"},
  "19": {"#ar": "التالي"},
  "20": {"#ar": "الترتيب: الافتراضي"},
  "21": {"#ar": "الترتيب: أفضل سعر"},
  "22": {"#ar": "الترتيب: سعر عالي"},
  "23": {"#ar": "العروض"},
  "24": {"#ar": "العقود"},
  "25": {"#ar": "الحساب"},
  "26": {"#ar": "الرجاء الاتصال بميتاماسك"},
  "27": {"#ar": "إيداع الرموز"},
  "28": {"#ar": "سحب الرموز"},
  "29": {"#ar": "معلومات الاتصال (البريد الإلكتروني/سيجنال/تليجرام):"},
  "30": {"#ar": "تسجيل المعلومات على عنواني (جهة الاتصال/التشفير/اختياري  )"},
  "31": {"#ar": "مسح العقود المكتملة تلقائيًا"},
  "32": {"#ar": "تحديث/استعادة العقود المحذوفة مسبقًا"},
  "33": {"#ar": "تنتهي العروض الخاصة: "},
  "34": {"#ar": "أبدًا"},
  "35": {"#ar": "أسبوعين"},
  "36": {"#ar": "شهر"},
  "37": {"#ar": "نسخ بيانات الموقع/المستخدم مؤقتًا"},
  "38": {"#ar": "تحميل بيانات الموقع/المستخدم من ملف"},
  "39": {"#ar": "استخدام بوابة IPFS الافتراضية لـ Pinata"},
  "40": {"#ar": "حول"},
  "41": {"#ar": "مرحبًا بك في عالم العقود القوية. هذه هي عقود الضمان ذات الطرفين (إيداع مزدوج) التي لا يمكن تحطيمها ولا تتطلب وسيطًا ثالثًا. يضع الطرفان إيداعًا قابلا للتخصيص جنبًا إلى جنب مع دفعة في حساب مشترك. إذا تمت الصفقة بنجاح، يوقع كل منهما عليها. إذا حاول أحد الأطراف الاحتيال على الآخر، ستنتهي الصفقة في النهاية وتنفجر، مما يجعل من الصعب الفوز بأي طرف ويصبح السرقة غير مربحة. هذا يجبر المستخدمين على أن يكونوا صادقين ويتبعوا التزاماتهم حيث يفوزون معًا أو يخسرون معًا."},
  "42": {"#ar": "تعمل الأسواق بشكل ذاتي على سلاسل Solidity مثل إيثيريوم وبوليغون. يمكن أن تتنوع العروض بين السلع والخدمات والتبادل وتداول نقطي إلى نقطي. نظرًا لأن هذه الصفحة واجهة ويب مفتوحة المصدر بالكامل وتعمل على جانب العميل، يمكن للمستخدم تنزيل هذا الكود من Github وتشغيله محليًا لتحقيق أمان أكبر. تمت تقنين هذا البروتوكول الذي قامت به بيت هالو لأول مرة في عام 2014 قبل إيثيريوم وكان أول عقود ذكية في العالم. هذه واجهة ويب للأسواق المفcentralة بالكامل."},
  "43": {"#ar": "لبيع السلع، سيكون المستخدمون بالتأكيد يرغبون في النظر في خدمة الشحن المباشر أو خدمة توفير شحن مخفض للتنافس مع أسعار الشحن التي تجدها عادة في الشركات الكبيرة. للقيام بذلك، يجب عليك التسجيل في حساب شحن طرف ثالث يسمح لك بتوفير حتى 75% في بعض الحالات. قد يفضل البائعون أيضًا تحصيل رسوم الشحن من المشترين أثناء الضمان المالي، وينبغي على المشترين أن يتحققوا من عدم تجاوز المبالغ المودعة أو أن يشتروا بطاقة الشحن بأنفسهم. ينبغي للمستخدمين أن يحاولوا البقاء على اتصال مع بعضهم البعض خلال عملية الضمان المالي ويُوصى بحفظ نسخة احتياطية من مفاتيحهم لحماية الطرفين خلال الضمان المالي. على الرغم من أن هذه الأسواق يمكن أن تكون تمترس من خلال الذكاء الاصطناعي (مثل WebGPT) والإدارة المشتركة من قبل المجتمع، يتحمل المستخدمون كامل المسؤولية عن مخاطر ما يقومون بنشره وعن ضماناتهم الخاصة. ومع ذلك، يتعين على المستخدمين عدم نشر محتوى غير قانوني في البلد الذي يقيمون فيه. بالنسبة للصفقات التي تنطوي على النقد، يجب على المستخدمين إجراء الفحص الدقيق وفحص العميل إذا لزم الأمر. يكون في مصلحة الجميع استخدام ضمان مالي مزدوج الودائع للتخلص من الخداع في عالم التجارة والخدمات الدولية. إنها ميزة عندما يدير المستخدمون العقود بأنفسهم لأن الحكام غير قادرين على معرفة حقيقة الصفقة مما يؤدي إلى قرارات غير عادلة ويمكنهم التواطؤ مما يسبب خسائر كبيرة ويتكبدون تكلفة أكبر. يُجبر المستخدمون على العمل مع بعضهم البعض لتحقيق نتيجة مرغوبة. المستخدمون هم أيضًا الذين يستضيفون العروض باستخدام نظام IPFS. لذلك يُفضل تشغيل عقدة IPFS الخاصة بك لأرشفة الأسواق. من المستحسن أن تقوم بتسجيل معلومات الاتصال الخاصة بك على سلسلة الكتل. يجعل هذا من المضمون أن الأطراف المعنية بالعقد تعرف كيفية الاتصال بك لطرح أي أسئلة حول التفاوض. يمكن تشغيل الشيفرة محلياً ويمكن أيضًا مراجعتها من خلال زيارة صفحة GitHub حيث يتم استضافة الشيفرة والموقع الإلكتروني. هذا النظام هو غير مملوك ومجاني تمامًا للاستخدام. ومع ذلك، هناك إعداد يمكن تنشيطه للشركات التابعة / الإحالات والتي يمكن أن تتراوح بين 0-1٪. من أجل تشجيع المستخدمين على التفاعل مع الشركاء التابعين، يتم حرق الرسوم إذا لم يتم دفعها إلى شركة تابعة. يساعد هذا في تسويق النظام عن طريق منح المستخدمين وسيلة لكسب الأرباح. يكون المستخدم للأسواق تلقائيًا شريكًا تابعًا إذا أكمل 10 صفقات. يتيح لهم ذلك استخدام الأسواق مجانًا إذا اختاروا ذلك (حيث يمكنهم أن يكونوا شركاء تابعين لأنفسهم) ويسمح لهم أيضًا بإرسال المستخدمين إلى الموقع من خلال رابط تابع. قد يقدم بعض البائعين أجرًا تابعًا أكثر جاذبية مما يسمح للشركاء بتحقيق المزيد بموافقة متبادلة. لمزيد من المعلومات حول كيفية عمل BitBay، يمكنك زيارة:"},
  "44":{"#ar":"كلمة المرور (للتشفير):"},
  "45":{"#ar":"كسب"},
  "46":{"#ar":"غير متصل"},
  "47":{"#ar":"نسخ الرابط التابع"},
  "48":{"#ar":"تغيير رابط الإحالة الخاص بي"},
  "49":{"#ar":"تعيين رسوم الإحالة المخصصة"},
  "50":{"#ar": "محاولة إخطار العملاء المحتملين عبر عميل البريد الإلكتروني الافتراضي (عند الاقتضاء)"}
};


languages['ch']={
  "1":{"#ch":"BitBay 去中心化市场"},
  "2":{"#ch":"BitBay 去中心化市场"},
  "3":{"#ch":"连接 Metamask"},
  "4":{"#ch":"未连接"},
  "5":{"#ch":"市场" },
  "6":{"#ch":"报价"},
  "7":{"#ch":"合同"},
  "8":{"#ch":"账户"},
  "9":{"#ch":"关于"},
  "10":{"#ch":"商品"},
  "11":{"#ch":"服务"},
  "12":{"#ch":"易货贸易"},
  "13":{"#ch":" P2P交易"},
  "14":{"#ch":"商品"},
  "15":{"#ch":"市场"},
  "16":{"#ch":"创建合同/报价"},
  "17":{"#ch":"搜索"},
  "18":{"#ch":"上一页 "},
  "19":{"#ch":"下一步"},
  "20":{"#ch":"排序：默认"},
  "21":{"#ch":"排序：最优惠价格"},
  "22":{"#ch":"排序：最高价格"},
  "23":{"#ch" :"优惠"},
  "24":{"#ch":"合同"},
  "25":{"#ch":"账户"},
  "26":{"#ch":"请连接元掩码"},
  "27":{"#ch":"充值代币"},
  "28":{"#ch":" 提取代币"},
  "29":{"#ch":"联系信息(电子邮件/信号/电报):"},
  "30":{"#ch":"注册信息到我的地址（联系人/加密/可选）"},
  "31":{"#ch":"自动清除已完成的合同"},
  "32":{"#ch":"刷新/恢复 之前清算的合同"},
  "33":{"#ch":"私人优惠到期:"},
  "34":{"#ch":"永不"},
  "35" :{"#ch":"两周"},
  "36":{"#ch":"一个月"},
  "37":{"#ch" :"备份缓存的站点/用户数据"},
  "38":{"#ch":"从文件加载站点/用户数据"},
  "39":{"#ch": "使用默认的 IPFS Pinata 网关"},
  "40":{"#ch":"关于"},
  "41":{"#ch":"欢迎来到牢不可破的合约世界 。 这些是两方托管（双倍存款）合约，无法被破坏，并且不需要第三方仲裁者。 两个用户都将可定制的存款和付款存入联名账户。 如果交易进展顺利，双方都会签字。 如果一方试图欺骗另一方，交易最终将到期并破裂，导致没有人获胜，盗窃也无利可图。 这迫使用户诚实并遵守协议，因为他们要么一起赢，要么一起输。"},
  "42":{"#ch":"市场本身在 Solidity 链之上运行 例如以太坊和Polygon。 优惠范围包括商品、服务、易货贸易和点对点交易。 由于该网页完全开源并在客户端运行，因此用户还可以从 github 下载此代码并在本地运行，以提高安全性。 该协议由 BitHalo 于 2014 年首创，早于以太坊，是世界上第一个智能合约。 这是一个基于网络的界面，适用于完全去中心化的市场。"},
  "43":{"#ch":"对于销售商品，用户肯定会考虑直接运输服务或提供折扣运输的服务，以与大公司通常提供的运费竞争。 为此，您应该注册第 3 方运输帐户，在某些情况下，该帐户可以让您节省高达 75% 的运费。 卖家还可能在托管期间向买家收取运费，买家应注意确保金额不超过押金，或者他们自己购买运输标签。 用户应尝试通过托管过程保持彼此通信，建议备份密钥，以便双方在托管期间都受到保护。 尽管这些市场可以通过人工智能（例如 webgpt）和社区驱动的审核来进行审核，但用户要对他们发布的内容和自己的托管承担全部责任。 考虑到这一点，强烈建议不要发布在您居住的国家/地区非法的内容。 对于涉及现金的交易，用户应自行尽职调查，并在需要时自行“了解您的客户”。 使用双重存款托管来消除国际商业和服务领域的欺诈行为符合每个人的最佳利益。 用户自己管理合约是一个优势，因为仲裁者无法知道不公平裁决的交易真相，并且可能串通造成巨大损失，同时也会产生更大成本。 用户被迫相互合作才能获得理想的结果。 用户也是使用 IPFS 托管商品的人。 因此，运行自己的 IPFS 节点来存档市场是一个很好的做法。 建议您将联系信息注册到区块链上。 这可以保证合同中的对方知道如何与您联系以解决有关谈判的任何问题。 代码可以在本地运行，也可以通过访问托管代码和网站的 github 页面进行审核。 该系统是无主的并且完全免费使用。 但是，可以为联营公司/推荐激活一个设置，范围为 0-1%。 为了鼓励用户与关联公司互动，如果不向关联公司支付费用，费用就会被烧毁。 这通过为用户提供赚钱的方式来帮助营销系统。 如果市场用户完成 10 笔交易，则自动成为会员。 如果他们选择的话，这允许他们免费使用市场（因为他们可以成为自己的附属机构），并且允许他们通过附属链接将用户发送到网站。 当交易被接受时，通过链接进行访问会将联属会员注册到该帐户，并让他们从该推荐中受益。 此外，一些卖家可能会提供更具吸引力的推荐费，这应该允许附属公司在双方同意的情况下获得更多净收入。 有关 BitBay 如何运作的更多信息，您可以访问： "},
  "44":{"#ch":"密码（用于加密）："},
  "45":{"#ch":"赚取"},
  "46":{"#ch":"未连接"},
  "47":{"#ch":"复制推广链接"},
  "48":{"#ch":"更改我的推广链接"},
  "49":{"#ch":"设置自定义推荐费"},
  "50":{"#ch": "尝试通过默认电子邮件客户端通知潜在客户（如果适用）"}
};

languages['en']={
  "1":{"#en":"BitBay Decentralized Markets"},
  "2":{"#en":"BitBay Decentralized Markets"},
  "3":{"#en":"Connect Metamask"},
  "4":{"#en":"Not connected"},
  "5":{"#en":"Markets"},
  "6":{"#en":"Offers"},
  "7":{"#en":"Contracts"},
  "8":{"#en":"Account"},
  "9":{"#en":"About"},
  "10":{"#en":"Goods"},
  "11":{"#en":"Services"},
  "12":{"#en":"Barter"},
  "13":{"#en":"P2P Trading"},
  "14":{"#en":"Commodities"},
  "15":{"#en":"Markets"},
  "16":{"#en":"Create Contract/Offer"},
  "17":{"#en":"Search"},
  "18":{"#en":"Previous"},
  "19":{"#en":"Next"},
  "20":{"#en":"Sort: Default"},
  "21":{"#en":"Sort: Best price"},
  "22":{"#en":"Sort: High price"},
  "23":{"#en":"Offers"},
  "24":{"#en":"Contracts"},
  "25":{"#en":"Account"},
  "26":{"#en":"Please connect metamask"},
  "27":{"#en":"Deposit tokens"},
  "28":{"#en":"Withdraw tokens"},
  "29":{"#en":"Contact Information(email/signal/telegram):"},
  "30":{"#en":"Register information to my address(contact/encryption/optional)"},
  "31":{"#en":"Automatically clear completed contracts"},
  "32":{"#en":"Refresh/restore previously cleared contracts"},
  "33":{"#en":"Private offers expire: "},
  "34":{"#en":"Never"},
  "35":{"#en":"Two weeks"},
  "36":{"#en":"One month"},
  "37":{"#en":"Backup cached site/user data"},
  "38":{"#en":"Load site/user data from file"},
  "39":{"#en":"Use default IPFS Pinata Gateway"},
  "40":{"#en":"About"},
  "41":{"#en":"Welcome to the world of unbreakable contracts. These are two party escrow(double deposit) contracts that cannot be broken and require no 3rd party arbiters. Both users place a customizable deposit along with a payment into a joint account. If the deal goes well they both sign off on it. If one party tries to defraud the other the deal will eventually expire and blow up making it so that nobody wins and theft is profitless. This forces the users to be honest and follow through with their agreements since they either win together or they lose together."},
  "42":{"#en":"The markets themselves run on top of Solidity chains such as Ethereum and Polygon. Offers can range from goods, services, barter and p2p trading. Since this webpage is fully open source and runs on the client side, the user can also download this code from github and run it locally for even greater security. This protocol which was pioneered by BitHalo back in 2014 predated Ethereum and was the worlds first smart contracts. This is a web based interface for fully decentralized markets."},
  "43":{"#en":"For selling goods, users will definitely want to consider a drop shipping service or a service that provides discount shipping to compete with the shipping rates typically found in major companies. To do this, you should sign up for a 3rd party shipping account which should allow you to save up to 75% in shipping in some cases. Sellers may also charge buyers for shipping while in escrow and buyers should be careful to make sure the amount doesn't exceed the deposits or that they buy the shipping label themselves. Users should try to keep in communication with each other through the escrow process and it's recommended to have a backup of your keys so both parties are protected during escrow. Although these markets could be moderated through AI(such as webgpt) and community driven moderation, users are entirely responsible for the risks of what they post and for their own escrows. With that in mind, it's strongly recommended to not post content that is illegal in the country you reside. For deals that involve cash users should do their own due dilligence and their own 'know your customer' if needed. It's in everyones best interest to use double deposit escrow to get rid of deception in the world of international commerce and services. It is an advantage when users administrate contracts themselves because arbiters are unable to know the truth of a deal ruling unfairly and can collude causing great losses and they also incur a greater cost. Users are forced to work with each other to achieve a desirable outcome. Users are also the ones who host the offers using IPFS. So it's good practice to run your own IPFS node to archive the markets. It's recommended that you register your contact information to the blockchain. This makes it guaranteed that counter-parties in the contract know how to contact you for any questions about the negotiations. The code may be run locally and can also be audited by visiting the github page where the code and website are hosted. This system is ownerless and entirely free to use. However, there is a setting that can be activated for affiliates/referrals which can range from 0-1%. In order to encourage users to engage with affiliates, the fee is burned if it is not paid to an affiliate. This helps market the system by giving users a way to earn. A user of the markets is automatically an affiliate if they complete 10 deals. That allows them to use the markets for free if they choose to(as they can be their own affiliate) and it allows them to send users to the website through an affiliate link. Visiting through a link registers the affiliate to that account when a deal is accepted and let's them benefit from that referral. Also, some sellers may offer a more attractive referral fee which should allow affiliates to net more by mutual consent. For more information on how BitBay works you may visit: "},
  "44":{"#en":"Password(for encryption):"},
  "45":{"#en":"Earn"},
  "46":{"#en":"Not connected"},
  "47":{"#en":"Copy affiliate link"},
  "48":{"#en":"Change my affiliate"},
  "49":{"#en":"Set custom referral fee"},
  "50":{"#en": "Attempt to notify prospects through default email client(when applicable)"}
};

languages['fr']={
  "1": {"#fr": "Marchés décentralisés BitBay"},
  "2": {"#fr": "Marchés décentralisés BitBay"},
  "3": {"#fr": "Connecter Metamask"},
  "4": {"#fr": "Non connecté"},
  "5": {"#fr": "Marchés"},
  "6": {"#fr": "Offres"},
  "7": {"#fr": "Contrats"},
  "8": {"#fr": "Compte"},
  "9": {"#fr": "À propos"},
  "10": {"#fr": "Biens"},
  "11": {"#fr": "Services"},
  "12": {"#fr": "Troquer"},
  "13": {"#fr": "Trading P2P"},
  "14": {"#fr": "Biens"},
  "15": {"#fr": "Marchés"},
  "16": {"#fr": "Créer un contrat/offre"},
  "17": {"#fr": "Rechercher"},
  "18": {"#fr": "Précédent"},
  "19": {"#fr": "Suivant"},
  "20": {"#fr": "Trier : Par défaut"},
  "21": {"#fr": "Trier : Meilleur prix"},
  "22": {"#fr": "Trier : Prix élevé"},
  "23": {"#fr": "Offres"},
  "24": {"#fr": "Contrats"},
  "25": {"#fr": "Compte"},
  "26": {"#fr": "Veuillez connecter Metamask"},
  "27": {"#fr": "Déposer des jetons"},
  "28": {"#fr": "Retirer des jetons"},
  "29": {"#fr": "Informations de contact (e-mail/signal/télégramme) :"},
  "30": {"#fr": "Enregistrer les informations à mon adresse (contact/cryptage/facultatif)"},
  "31": {"#fr": "Effacer automatiquement les contrats terminés"},
  "32": {"#fr": "Actualiser/restaurer les contrats préalablement effacés"},
  "33": {"#fr": "Les offres privées expirent : "},
  "34": {"#fr": "Jamais"},
  "35": {"#fr": "Deux semaines"},
  "36": {"#fr": "Un mois"},
  "37": {"#fr": "Sauvegarder les données temporaires du site/de l'utilisateur"},
  "38": {"#fr": "Charger les données du site/de l'utilisateur à partir d'un fichier"},
  "39": {"#fr": "Utiliser la passerelle IPFS par défaut de Pinata"},
  "40": {"#fr": "À propos"},
  "41": {"#fr": "Bienvenue dans le monde des contrats incassables. Ce sont des contrats d'entiercement à deux parties (double dépôt) qui ne peuvent pas être rompus et ne nécessitent aucun arbitre tiers. Les deux utilisateurs placent un dépôt personnalisable ainsi qu'un paiement dans un compte commun. Si l'affaire se déroule bien, ils signent tous les deux. Si l'une des parties tente de tromper l'autre, l'affaire expirera finalement et éclatera, de sorte que personne ne gagne et le vol est sans profit. Cela force les utilisateurs à être honnêtes et à respecter leurs accords, car ils gagnent ensemble ou perdent ensemble."},
  "42": {"#fr": "Les marchés eux-mêmes fonctionnent sur des chaînes Solidity telles qu'Ethereum et Polygon. Les offres peuvent varier des biens, des services, du troc et du trading P2P. Puisque cette page web est entièrement open source et s'exécute côté client, l'utilisateur peut également télécharger ce code depuis GitHub et l'exécuter localement pour une sécurité accrue. Ce protocole, pionnier de BitHalo en 2014, a précédé Ethereum et était le tout premier contrat intelligent au monde. Il s'agit d'une interface Web pour des marchés entièrement décentralisés."},
  "43": {"#fr": "Pour vendre des marchandises, les utilisateurs voudront certainement envisager un service de livraison directe ou un service offrant une expédition à prix réduit pour rivaliser avec les tarifs d'expédition généralement trouvés dans les grandes entreprises. Pour ce faire, vous devez créer un compte d'expédition tiers qui devrait vous permettre d'économiser jusqu'à 75 % sur les frais d'expédition dans certains cas. Les vendeurs peuvent également facturer aux acheteurs les frais d'expédition lorsqu'ils sont sous séquestre et les acheteurs doivent veiller à ce que le montant ne dépasse pas les dépôts ou à acheter eux-mêmes l'étiquette d'expédition. Les utilisateurs doivent essayer de rester en communication les uns avec les autres via le processus de dépôt et il est recommandé d'avoir une sauvegarde de vos clés afin que les deux parties soient protégées pendant le dépôt. Bien que ces marchés puissent être modérés par l'IA (comme webgpt) et par la modération communautaire, les utilisateurs sont entièrement responsables des risques liés à ce qu'ils publient et de leurs propres dépôts. Dans cette optique, il est fortement recommandé de ne pas publier de contenu illégal dans le pays dans lequel vous résidez. Pour les transactions impliquant des espèces, les utilisateurs doivent faire leur propre diligence raisonnable et leur propre « connaissance de votre client » si nécessaire. Il est dans l’intérêt de tous d’utiliser le double dépôt séquestre pour se débarrasser de la tromperie dans le monde du commerce et des services internationaux. C'est un avantage lorsque les utilisateurs administrent eux-mêmes les contrats, car les arbitres sont incapables de connaître la vérité sur un accord injuste et peuvent s'entendre, causant de lourdes pertes et supportant également un coût plus élevé. Les utilisateurs sont obligés de travailler les uns avec les autres pour obtenir un résultat souhaité. Ce sont également les utilisateurs qui hébergent les offres via IPFS. C'est donc une bonne pratique d'exécuter votre propre nœud IPFS pour archiver les marchés. Il est recommandé d'enregistrer vos coordonnées sur la blockchain. Cela garantit que les contreparties au contrat savent comment vous contacter pour toute question concernant les négociations. Le code peut être exécuté localement et peut également être audité en visitant la page github où le code et le site Web sont hébergés. Ce système est sans propriétaire et entièrement gratuit. Cependant, il existe un paramètre qui peut être activé pour les affiliés/références qui peut aller de 0 à 1 %. Afin d'encourager les utilisateurs à interagir avec les affiliés, les frais sont brûlés s'ils ne sont pas payés à un affilié. Cela aide à commercialiser le système en donnant aux utilisateurs un moyen de gagner de l'argent. Un utilisateur des marchés est automatiquement affilié s’il réalise 10 transactions. Cela leur permet d'utiliser les marchés gratuitement s'ils le souhaitent (car ils peuvent être leur propre affilié) et cela leur permet d'envoyer des utilisateurs vers le site Web via un lien d'affiliation. La visite via un lien enregistre l'affilié sur ce compte lorsqu'une offre est acceptée et lui permet de bénéficier de cette référence. En outre, certains vendeurs peuvent proposer des frais de parrainage plus attractifs, ce qui devrait permettre aux affiliés de gagner davantage par consentement mutuel. Pour plus d'informations sur le fonctionnement de BitBay, vous pouvez visiter: "},
  "44": {"#fr": "Mot de passe (pour le cryptage) :"},
  "45": {"#fr": "Gagner"},
  "46": {"#fr": "Non connecté"},
  "47": {"#fr": "Copier le lien d'affiliation"},
  "48": {"#fr": "Changer mon lien d'affiliation"},
  "49": {"#fr": "Définir des frais de parrainage personnalisés"},
  "50": {"#fr": "Tentative de notifier les prospects via le client de messagerie électronique par défaut (si applicable)"}
};

languages['ge']={
  "1": {"#ge": "BitBay Dezentralisierte Märkte"},
  "2": {"#ge": "BitBay Dezentralisierte Märkte"},
  "3": {"#ge": "Metamask verbinden"},
  "4": {"#ge": "Nicht verbunden"},
  "5": {"#ge": "Märkte"},
  "6": {"#ge": "Angebote"},
  "7": {"#ge": "Verträge"},
  "8": {"#ge": "Konto"},
  "9": {"#ge": "Über uns"},
  "10": {"#ge": "Waren"},
  "11": {"#ge": "Dienstleistungen"},
  "12": {"#ge": "Tauschhandel"},
  "13": {"#ge": "P2P-Handel"},
  "14": {"#ge": "Güter"},
  "15": {"#ge": "Märkte"},
  "16": {"#ge": "Vertrag/Angebot erstellen"},
  "17": {"#ge": "Suchen"},
  "18": {"#ge": "Vorherige"},
  "19": {"#ge": "Nächste"},
  "20": {"#ge": "Sortieren: Standard"},
  "21": {"#ge": "Sortieren: Bester Preis"},
  "22": {"#ge": "Sortieren: Hoher Preis"},
  "23": {"#ge": "Angebote"},
  "24": {"#ge": "Verträge"},
  "25": {"#ge": "Konto"},
  "26": {"#ge": "Bitte Metamask verbinden"},
  "27": {"#ge": "Token einzahlen"},
  "28": {"#ge": "Token abheben"},
  "29": {"#ge": "Kontaktinformationen (E-Mail/Signal/Telegramm):"},
  "30": {"#ge": "Registrierungsinformationen an meine Adresse (Kontakt/Verschlüsselung/optional)"},
  "31": {"#ge": "Abgeschlossene Verträge automatisch löschen"},
  "32": {"#ge": "Zuvor gelöschte Verträge aktualisieren/wiederherstellen"},
  "33": {"#ge": "Private Angebote laufen ab: "},
  "34": {"#ge": "Nie"},
  "35": {"#ge": "Zwei Wochen"},
  "36": {"#ge": "Ein Monat"},
  "37": {"#ge": "Gespeicherte Website-/Benutzerdaten sichern"},
  "38": {"#ge": "Website-/Benutzerdaten aus Datei laden"},
  "39": {"#ge": "Standard-IPFS-Pinata-Gateway verwenden"},
  "40": {"#ge": "Über uns"},
  "41": {"#ge": "Willkommen in der Welt der unzerbrechlichen Verträge. Dies sind Zweiparteien-Escrow(Doppeldatenträger)-Verträge, die nicht gebrochen werden können und keine Schiedsrichter von Dritten erfordern. Beide Benutzer legen eine anpassbare Kaution zusammen mit einer Zahlung auf ein gemeinsames Konto. Wenn die Transaktion gut verläuft, unterzeichnen beide. Wenn eine Partei versucht, die andere zu betrügen, wird die Transaktion schließlich ablaufen und scheitern, sodass niemand gewinnt und Diebstahl nutzlos ist. Dies zwingt die Benutzer, ehrlich zu sein und ihre Vereinbarungen einzuhalten, da sie entweder gemeinsam gewinnen oder gemeinsam verlieren."},
  "42": {"#ge": "Die Märkte selbst laufen auf Solidity-Ketten wie Ethereum und Polygon. Angebote können von Waren, Dienstleistungen, Tauschhandel bis hin zu P2P-Handel reichen. Da diese Webseite vollständig Open Source ist und auf der Client-Seite läuft, kann der Benutzer diesen Code auch von GitHub herunterladen und lokal ausführen, um noch mehr Sicherheit zu gewährleisten. Dieses Protokoll, das von BitHalo bereits 2014 entwickelt wurde, ging Ethereum voraus und war der weltweit erste intelligente Vertrag. Dies ist eine webbasierte Benutzeroberfläche für vollständig dezentralisierte Märkte."},
  "43": {"#ge": "Für den Verkauf von Waren sollten Benutzer auf jeden Fall einen Drop-Shipping-Service oder einen Service in Betracht ziehen, der Rabattversand bietet, um mit den Versandtarifen zu konkurrieren, die normalerweise bei großen Unternehmen gelten. Dazu sollten Sie sich für ein Drittanbieter-Versandkonto anmelden, mit dem Sie in manchen Fällen bis zu 75 % beim Versand sparen können. Verkäufer können Käufern auch Gebühren für den Versand in Rechnung stellen, während sie sich im Treuhandkonto befinden. Käufer sollten darauf achten, dass der Betrag die Anzahlung nicht übersteigt oder dass sie das Versandetikett selbst kaufen. Benutzer sollten versuchen, während des Treuhandprozesses miteinander in Kommunikation zu bleiben. Es wird empfohlen, eine Sicherungskopie Ihrer Schlüssel zu erstellen, damit beide Parteien während des Treuhandprozesses geschützt sind. Obwohl diese Märkte durch KI (z. B. webgpt) und Community-gesteuerte Moderation moderiert werden könnten, sind die Benutzer vollständig für die Risiken ihrer Beiträge und für ihre eigenen Treuhandkonten verantwortlich. Vor diesem Hintergrund wird dringend empfohlen, keine Inhalte zu veröffentlichen, die in dem Land, in dem Sie leben, illegal sind. Bei Geschäften, bei denen es um Bargeld geht, sollten Benutzer ihre eigene Due-Diligence-Prüfung durchführen und bei Bedarf ihre eigene „Know Your Customer“-Methode anwenden. Es liegt im Interesse aller, ein doppeltes Einzahlungs-Treuhandkonto zu nutzen, um Täuschungen in der Welt des internationalen Handels und der internationalen Dienstleistungen zu beseitigen. Es ist von Vorteil, wenn Benutzer Verträge selbst verwalten, da Schiedsrichter nicht in der Lage sind, den Wahrheitsgehalt eines zu Unrecht entschiedenen Geschäfts zu erfahren, und Absprachen treffen können, die große Verluste verursachen und auch höhere Kosten verursachen. Benutzer sind gezwungen, zusammenzuarbeiten, um ein gewünschtes Ergebnis zu erzielen. Benutzer sind auch diejenigen, die die Angebote über IPFS hosten. Daher empfiehlt es sich, einen eigenen IPFS-Knoten zu betreiben, um die Märkte zu archivieren. Es wird empfohlen, dass Sie Ihre Kontaktinformationen in der Blockchain registrieren. Dadurch ist sichergestellt, dass die Vertragsparteien wissen, wie sie Sie bei Fragen zu den Verhandlungen kontaktieren können. Der Code kann lokal ausgeführt werden und kann auch überprüft werden, indem man die Github-Seite besucht, auf der der Code und die Website gehostet werden. Dieses System ist eigentümerlos und völlig kostenlos zu nutzen. Es gibt jedoch eine aktivierbare Einstellung für Affiliates/Empfehlungen, die zwischen 0 und 1 % liegen kann. Um Benutzer zu ermutigen, mit Partnern in Kontakt zu treten, wird die Gebühr verbrannt, wenn sie nicht an einen Partner gezahlt wird. Dies hilft bei der Vermarktung des Systems, indem es den Benutzern eine Möglichkeit bietet, Geld zu verdienen. Ein Nutzer der Märkte ist automatisch ein Affiliate, wenn er 10 Deals abschließt. Dadurch können sie die Märkte bei Bedarf kostenlos nutzen (da sie ihr eigener Affiliate sein können) und Benutzer über einen Affiliate-Link auf die Website weiterleiten. Durch den Besuch über einen Link wird der Partner bei der Annahme eines Deals für dieses Konto registriert und kann von dieser Empfehlung profitieren. Einige Verkäufer bieten möglicherweise auch eine attraktivere Empfehlungsgebühr an, die es Affiliates ermöglichen sollte, im gegenseitigen Einvernehmen mehr zu verdienen. Weitere Informationen zur Funktionsweise von BitBay finden Sie unter: "},
  "44": {"#ge": "Passwort (für Verschlüsselung):"},
  "45": {"#ge": "Verdienen"},
  "46": {"#ge": "Nicht verbunden"},
  "47": {"#ge": "Affiliate-Link kopieren"},
  "48": {"#ge": "Meinen Affiliate-Link ändern"},
  "49": {"#ge": "Benutzerdefinierte Empfehlungsgebühr festlegen"},
  "50": {"#ge": "Versuch, potenzielle Kunden über den Standard-E-Mail-Client zu benachrichtigen (falls zutreffend)"}
};

languages['it']={
  "1": {"#it": "BitBay Mercati Decentralizzati"},
  "2": {"#it": "BitBay Mercati Decentralizzati"},
  "3": {"#it": "Collega Metamask"},
  "4": {"#it": "Non connesso"},
  "5": {"#it": "Mercati"},
  "6": {"#it": "Offerte"},
  "7": {"#it": "Contratti"},
  "8": {"#it": "Account"},
  "9": {"#it": "Informazioni"},
  "10": {"#it": "Merci"},
  "11": {"#it": "Servizi"},
  "12": {"#it": "Baratto"},
  "13": {"#it": "Trading P2P"},
  "14": {"#it": "Commodities"},
  "15": {"#it": "Mercati"},
  "16": {"#it": "Crea Contratto/Offerta"},
  "17": {"#it": "Cerca"},
  "18": {"#it": "Precedente"},
  "19": {"#it": "Successivo"},
  "20": {"#it": "Ordina: Predefinito"},
  "21": {"#it": "Ordina: Miglior prezzo"},
  "22": {"#it": "Ordina: Prezzo alto"},
  "23": {"#it": "Offerte"},
  "24": {"#it": "Contratti"},
  "25": {"#it": "Account"},
  "26": {"#it": "Si prega di collegare Metamask"},
  "27": {"#it": "Deposita token"},
  "28": {"#it": "Preleva token"},
  "29": {"#it": "Informazioni di contatto (email/signal/telegramma):"},
  "30": {"#it": "Registra le informazioni al mio indirizzo (contatto/crittografia/opzionale)"},
  "31": {"#it": "Elimina automaticamente i contratti completati"},
  "32": {"#it": "Aggiorna/ripristina contratti precedentemente eliminati"},
  "33": {"#it": "Le offerte private scadono: "},
  "34": {"#it": "Mai"},
  "35": {"#it": "Due settimane"},
  "36": {"#it": "Un mese"},
  "37": {"#it": "Backup dati del sito/dell'utente"},
  "38": {"#it": "Carica dati del sito/dell'utente da file"},
  "39": {"#it": "Usa l'IPFS Pinata Gateway predefinito"},
  "40": {"#it": "Informazioni"},
  "41": {"#it": "Benvenuti nel mondo dei contratti indistruttibili. Questi sono contratti di escrow a doppio deposito che coinvolgono due parti e non possono essere infranti e non richiedono arbitri di terze parti. Entrambi gli utenti versano un deposito personalizzabile insieme a un pagamento su un conto congiunto. Se l'affare va bene, entrambi lo convalidano. Se una parte cerca di truffare l'altra, l'affare alla fine scade e fallisce, in modo che nessuno vinca e il furto sia inutile. Ciò costringe gli utenti a essere onesti e a rispettare i loro accordi, poiché o vincono insieme o perdono insieme."},
  "42": {"#it": "I mercati stessi funzionano su catene Solidity come Ethereum e Polygon. Le offerte possono spaziare da merci, servizi, baratto e trading P2P. Poiché questa pagina web è completamente open source e funziona lato client, l'utente può anche scaricare questo codice da GitHub e eseguirlo localmente per una sicurezza ancora maggiore. Questo protocollo, che è stato introdotto per la prima volta da BitHalo nel 2014, precede Ethereum ed è stato il primo contratto intelligente al mondo. Questa è un'interfaccia basata sul web per mercati completamente decentralizzati."},
  "43": {"#it": "Per la vendita di beni, gli utenti vorranno sicuramente prendere in considerazione un servizio di drop shipping o un servizio che offra spedizioni scontate per competere con le tariffe di spedizione tipicamente presenti nelle principali aziende. Per fare ciò, dovresti registrarti per un account di spedizione di terze parti che dovrebbe consentirti di risparmiare fino al 75% sulla spedizione in alcuni casi. I venditori possono anche addebitare agli acquirenti la spedizione mentre sono in deposito a garanzia e gli acquirenti devono fare attenzione ad assicurarsi che l'importo non superi i depositi o ad acquistare essi stessi l'etichetta di spedizione. Gli utenti dovrebbero cercare di rimanere in comunicazione tra loro attraverso il processo di deposito a garanzia ed è consigliabile avere un backup delle chiavi in modo che entrambe le parti siano protette durante il deposito a garanzia. Sebbene questi mercati possano essere moderati tramite l’intelligenza artificiale (come webgpt) e la moderazione guidata dalla comunità, gli utenti sono interamente responsabili dei rischi di ciò che pubblicano e dei propri depositi a garanzia. Tenendo questo a mente, ti consigliamo vivamente di non pubblicare contenuti illegali nel Paese in cui risiedi. Per le operazioni che coinvolgono contanti, gli utenti dovrebbero effettuare la propria due diligence e, se necessario, 'conoscere il proprio cliente'. È nell'interesse di tutti utilizzare il doppio deposito a garanzia per eliminare l'inganno nel mondo del commercio e dei servizi internazionali. È un vantaggio quando gli utenti amministrano autonomamente i contratti perché gli arbitri non sono in grado di conoscere la verità di un accordo che si pronuncia ingiustamente e possono colludere causando grandi perdite e sostenendo anche un costo maggiore. Gli utenti sono costretti a collaborare tra loro per ottenere un risultato desiderabile. Gli utenti sono anche coloro che ospitano le offerte utilizzando IPFS. Quindi è buona pratica eseguire il proprio nodo IPFS per archiviare i mercati. Ti consigliamo di registrare le tue informazioni di contatto sulla blockchain. Ciò garantisce che le controparti del contratto sappiano come contattarti per qualsiasi domanda sulle negoziazioni. Il codice può essere eseguito localmente e può anche essere controllato visitando la pagina github in cui sono ospitati il codice e il sito web. Questo sistema è senza proprietario e completamente gratuito da usare. Tuttavia, esiste un'impostazione che può essere attivata per gli affiliati/referral che può variare dallo 0 all'1%. Per incoraggiare gli utenti a interagire con gli affiliati, la commissione viene bruciata se non viene pagata a un affiliato. Ciò aiuta a commercializzare il sistema offrendo agli utenti un modo per guadagnare. Un utente dei mercati è automaticamente affiliato se completa 10 operazioni. Ciò consente loro di utilizzare i mercati gratuitamente se lo desiderano (poiché possono essere i propri affiliati) e consente loro di inviare utenti al sito Web tramite un collegamento di affiliazione. La visita tramite un collegamento registra l'affiliato su quell'account quando un accordo viene accettato e permette loro di beneficiare di quel riferimento. Inoltre, alcuni venditori potrebbero offrire una commissione di riferimento più interessante che dovrebbe consentire agli affiliati di guadagnare di più di comune accordo. Per ulteriori informazioni su come funziona BitBay puoi visitare: "},
  "44": {"#it": "Password (per crittografia):"},
  "45": {"#it": "Guadagna"},
  "46": {"#it": "Non connesso"},
  "47": {"#it": "Copia il link di affiliazione"},
  "48": {"#it": "Cambia il mio link di affiliazione"},
  "49": {"#it": "Imposta la tariffa di referral personalizzata"},
  "50": {"#it": "Tentativo di notificare i potenziali clienti tramite il client di posta elettronica predefinito (quando applicabile)"}
};

languages['ja']={
  "1":{"#ja":"BitBay 分散型市場"},
  "2":{"#ja":"BitBay 分散型市場"},
  "3":{"#ja":"メタマスクに接続"},
  "4":{"#ja":"接続されていません"},
  "5":{"#ja":"マーケット"},
  "6":{"#ja":"オファー"},
  "7":{"#ja":"契約"},
  "8":{"#ja":"アカウント"},
  "9":{"#ja":"概要"},
  "10":{"#ja":"グッズ"},
  "11":{"#ja":"サービス"},
  "12":{"#ja":"物々交換"},
  "13":{"#ja":" P2P 取引"},
  "14":{"#ja":"商品"},
  "15":{"#ja":"市場"},
  "16":{"#ja":"契約/オファーの作成"},
  "17":{"#ja":"検索"},
  "18":{"#ja":"前へ "},
  "19":{"#ja":"次へ"},
  "20":{"#ja":"並べ替え: デフォルト"},
  "21":{"#ja":"並べ替え: 価格が安い"},
  "22":{"#ja":"並べ替え: 価格が高い"},
  "23":{"#ja" :"オファー"},
  "24":{"#ja":"契約"},
  "25":{"#ja":"アカウント"},
  "26":{"#ja":"メタマスクを接続してください"},
  "27":{"#ja":"トークンを入金"},
  "28":{"#ja":" トークンの引き出し"},
  "29":{"#ja":"連絡先情報(メール/シグナル/電報):"},
  "30":{"#ja":"マイアドレスに情報を登録（連絡先/暗号化/任意）"},
  "31":{"#ja":"完了した契約を自動的にクリア"},
  "32":{"#ja":"更新/復元 以前にクリアされた契約"},
  "33":{"#ja":"プライベートオファーの有効期限: "},
  "34":{"#ja":"なし"},
  "35":{"#ja":"2 週間"},
  "36":{"#ja":"1 か月"},
  "37":{"#ja" :"キャッシュされたサイト/ユーザー データをバックアップします"},
  "38":{"#ja":"サイト/ユーザー データをファイルからロードします"},
  "39":{"#ja": "デフォルトの IPFS Pinata ゲートウェイを使用する"},
  "40":{"#ja":"概要"},
  "41":{"#ja":"破られない契約の世界へようこそ 。 これらは二者間のエスクロー（二重預金）契約であり、破棄することはできず、第三者の仲裁人を必要としません。 両方のユーザーは、共同アカウントへの支払いとともにカスタマイズ可能な入金を行います。 取引がうまくいけば、両者は契約を締結します。 一方の当事者がもう一方の当事者をだまそうとすると、最終的には取引が期限切れになり、誰も得をせず、窃盗は利益を生みません。 これにより、ユーザーは、一緒に勝つか一緒に負けるかのどちらかであるため、正直になり、契約を最後まで遵守する必要があります。"},
  "42":{"#ja":"市場自体は Solidity チェーンの上で運営されています。 イーサリアムやポリゴンなど。 オファーは、商品、サービス、物々交換、P2P 取引など多岐にわたります。 この Web ページは完全にオープン ソースであり、クライアント側で実行されるため、ユーザーはこのコードを github からダウンロードしてローカルで実行して、セキュリティをさらに強化することもできます。 2014 年に BitHalo によって開発されたこのプロトコルは、イーサリアムよりも前であり、世界初のスマート コントラクトでした。 これは、完全に分散化された市場向けの Web ベースのインターフェイスです。"},
  "43":{"#ja":"商品を販売する場合、ユーザーはドロップシッピングサービスや、大手企業で一般的に見られる配送料に対抗するために割引配送を提供するサービスを必ず検討したいと思うでしょう。 これを行うには、場合によっては配送料を最大 75% 節約できるサードパーティの配送アカウントにサインアップする必要があります。 売り手はエスクロー中に買い手に送料を請求することもあります。買い手は金額が保証金を超えないように注意するか、自分で配送ラベルを購入するように注意する必要があります。 ユーザーはエスクロー プロセスを通じて相互に通信を維持するように努める必要があり、エスクロー中に双方が保護されるようにキーのバックアップを作成することをお勧めします。 これらの市場は AI (webgpt など) やコミュニティ主導のモデレーションを通じてモデレートできますが、投稿内容のリスクと自分のエスクローについてはユーザーが全責任を負います。 このことを念頭に置いて、お住まいの国で違法なコンテンツを投稿しないことを強くお勧めします。 現金を伴う取引の場合、ユーザーは必要に応じて独自のデューデリジェンスを行い、「顧客を知る」必要があります。 国際商取引およびサービスの世界で詐欺行為を排除するために二重預金エスクローを使用することは、誰にとっても最大の利益になります。 仲裁人は不当な取引裁定の真実を知ることができず、共謀して多大な損失を引き起こす可能性があり、またより大きなコストも発生する可能性があるため、ユーザーが契約を自分で管理する場合にはこれが利点となります。 ユーザーは望ましい結果を達成するために互いに協力する必要があります。 ユーザーは、IPFS を使用してオファーをホストする人でもあります。 したがって、独自の IPFS ノードを実行して市場をアーカイブすることをお勧めします。 連絡先情報をブロックチェーンに登録することをお勧めします。 これにより、契約の相手方は、交渉に関する質問がある場合にあなたに連絡する方法を確実に知ることができます。 コードはローカルで実行でき、コードと Web サイトがホストされている github ページにアクセスして監査することもできます。 このシステムには所有者がなく、完全に無料で使用できます。 ただし、アフィリエイト/紹介に対して有効化できる設定があり、その範囲は 0 ～ 1% です。 ユーザーにアフィリエイトへの参加を促すため、アフィリエイトに料金が支払われない場合、料金は無駄になります。 これにより、ユーザーに収入を得る方法が提供され、システムのマーケティングに役立ちます。 マーケットのユーザーは、10 件の取引を完了すると、自動的にアフィリエイトになります。 これにより、必要に応じて (独自のアフィリエイトになれるため) マーケットを無料で使用できるようになり、アフィリエイト リンクを通じてユーザーを Web サイトに誘導できるようになります。 リンクを通じてアクセスすると、取引が受け入れられたときにアフィリエイトがそのアカウントに登録され、その紹介の恩恵を受けることができます。 また、販売者の中には、より魅力的な紹介料を提示する場合もあり、これによりアフィリエイターは相互の合意によりより多くの利益を得ることができます。 BitBay の仕組みの詳細については、次のサイトをご覧ください。"},
  "44":{"#ja": "パスワード（暗号化用）："},
  "45":{"#ja": "稼ぐ"},
  "46":{"#ja": "未接続"},
  "47":{"#ja": "アフィリエイトリンクをコピー"},
  "48":{"#ja": "私のアフィリエイトを変更"},
  "49":{"#ja": "カスタム紹介手数料を設定"},
  "50":{"#ja": "（該当する場合）デフォルトの電子メールクライアントを介して見込み顧客に通知を試みる"} 
};

languages['ko']={
  "1": {"#ko": "BitBay 탈중앙화된 시장"},
  "2": {"#ko": "BitBay 탈중앙화된 시장"},
  "3": {"#ko": "Metamask 연결"},
  "4": {"#ko": "연결되지 않음"},
  "5": {"#ko": "시장"},
  "6": {"#ko": "제안"},
  "7": {"#ko": "계약"},
  "8": {"#ko": "계정"},
  "9": {"#ko": "소개"},
  "10": {"#ko": "상품"},
  "11": {"#ko": "서비스"},
  "12": {"#ko": "물물 교환"},
  "13": {"#ko": "P2P 트레이딩"},
  "14": {"#ko": "상품"},
  "15": {"#ko": "시장"},
  "16": {"#ko": "계약/제안 생성"},
  "17": {"#ko": "검색"},
  "18": {"#ko": "이전"},
  "19": {"#ko": "다음"},
  "20": {"#ko": "정렬: 기본값"},
  "21": {"#ko": "정렬: 최저 가격"},
  "22": {"#ko": "정렬: 높은 가격"},
  "23": {"#ko": "제안"},
  "24": {"#ko": "계약"},
  "25": {"#ko": "계정"},
  "26": {"#ko": "Metamask를 연결하십시오."},
  "27": {"#ko": "토큰 입금"},
  "28": {"#ko": "토큰 출금"},
  "29": {"#ko": "연락처 정보(이메일/signal/텔레그램):"},
  "30": {"#ko": "내 주소에 정보 등록(연락처/암호화/선택)"},
  "31": {"#ko": "자동으로 완료된 계약 지우기"},
  "32": {"#ko": "이전에 지워진 계약 새로고침/복원"},
  "33": {"#ko": "개인 제안 만료: "},
  "34": {"#ko": "안 함"},
  "35": {"#ko": "두 주"},
  "36": {"#ko": "한 달"},
  "37": {"#ko": "캐시된 사이트/사용자 데이터 백업"},
  "38": {"#ko": "파일에서 사이트/사용자 데이터 불러오기"},
  "39": {"#ko": "기본 IPFS Pinata 게이트웨이 사용"},
  "40": {"#ko": "소개"},
  "41": {"#ko": "파괴할 수 없는 계약의 세계에 오신 것을 환영합니다. 이들은 깨질 수 없는 이중 예치금 계약으로, 3자 중재인이 필요하지 않습니다. 양측 사용자는 맞춤형 예치금과 함께 공동 계정에 지불을 넣습니다. 거래가 성공하면 양측이 서명합니다. 한 쪽이 상대방을 사기하려고하면 거래는 결국 만료되어 실패하며 아무도 이기지 못하고 도난은 이익이 없게 됩니다. 이로써 사용자는 성실하고 합의를 따르도록 강제됩니다. 그들은 함께 이기거나 함께 지거나 둘 중 하나입니다."},
  "42": {"#ko": "시장 자체는 Ethereum 및 Polygon과 같은 Solidity 체인 위에서 실행됩니다. 상품, 서비스, 물물 교환 및 P2P 거래까지 제안이 다양할 수 있습니다. 이 웹페이지는 완전히 오픈 소스이며 클라이언트 측에서 실행되므로 사용자는 GitHub에서 이 코드를 다운로드하여 로컬에서 실행할 수도 있습니다. 이 프로토콜은 2014년 BitHalo에서 개척되었으며 Ethereum 이전에 세계 최초의 스마트 계약이었습니다. 이는 완전히 탈중앙화된 시장을 위한 웹 기반 인터페이스입니다."},
  "43": {"#ko": "상품 판매를 위해 사용자는 직송 서비스 또는 주요 회사에서 일반적으로 볼 수 있는 배송료와 경쟁하기 위해 할인 배송을 제공하는 서비스를 고려하고 싶어할 것입니다. 이렇게 하려면 경우에 따라 배송비를 최대 75%까지 절약할 수 있는 제3자 배송 계정에 가입해야 합니다. 판매자는 에스크로 상태에서 구매자에게 배송비를 청구할 수도 있으며, 구매자는 해당 금액이 예치금을 초과하지 않도록 주의하거나 배송 라벨을 직접 구매해야 합니다. 사용자는 에스크로 프로세스를 통해 서로 계속 통신해야 하며 에스크로 중에 두 당사자 모두를 보호할 수 있도록 키를 백업해 두는 것이 좋습니다. 이러한 시장은 AI(예: webgpt) 및 커뮤니티 중심 조정을 통해 조정될 수 있지만 사용자는 자신이 게시하는 내용의 위험과 자신의 에스크로에 대해 전적으로 책임을 집니다. 이를 염두에 두고, 귀하가 거주하는 국가에서 불법인 콘텐츠를 게시하지 않는 것이 좋습니다. 현금이 포함된 거래의 경우 사용자는 스스로 실사를 수행하고 필요한 경우 '고객을 파악'해야 합니다. 국제 상거래 및 서비스 세계에서 사기를 없애기 위해 이중 예금 에스크로를 사용하는 것은 모든 사람에게 가장 큰 이익이 됩니다. 중재자는 부당하게 판결된 거래의 진실을 알 수 없고 공모하여 큰 손실을 입을 수 있으며 더 많은 비용이 발생하기 때문에 사용자가 직접 계약을 관리할 때 이점이 있습니다. 사용자는 바람직한 결과를 얻기 위해 서로 협력해야 합니다. 사용자는 IPFS를 사용하여 제안을 호스팅하는 사람이기도 합니다. 따라서 자체 IPFS 노드를 실행하여 시장을 보관하는 것이 좋습니다. 블록체인에 연락처 정보를 등록하는 것이 좋습니다. 이를 통해 계약 상대방이 협상에 대한 질문이 있는 경우 귀하에게 연락할 수 있는 방법을 알 수 있습니다. 코드는 로컬에서 실행될 수 있으며 코드와 웹사이트가 호스팅되는 github 페이지를 방문하여 감사할 수도 있습니다. 이 시스템은 소유자가 없으며 완전히 무료로 사용할 수 있습니다. 그러나 0~1% 범위의 제휴사/추천에 대해 활성화할 수 있는 설정이 있습니다. 사용자가 제휴사와 교류하도록 유도하기 위해 제휴사에 지불되지 않으면 수수료가 소각됩니다. 이는 사용자에게 수익을 창출할 수 있는 방법을 제공함으로써 시스템을 마케팅하는 데 도움이 됩니다. 시장 사용자는 10개의 거래를 완료하면 자동으로 제휴사가 됩니다. 이를 통해 원하는 경우 시장을 무료로 사용할 수 있으며(자신의 제휴사가 될 수 있으므로) 제휴 링크를 통해 사용자를 웹사이트로 보낼 수 있습니다. 링크를 통해 방문하면 거래가 승인될 때 제휴사가 해당 계정에 등록되고 해당 추천으로부터 혜택을 받을 수 있습니다. 또한 일부 판매자는 제휴사가 상호 동의를 통해 더 많은 수익을 올릴 수 있도록 보다 매력적인 추천 수수료를 제공할 수 있습니다. BitBay 작동 방식에 대한 자세한 내용을 보려면 다음 사이트를 방문하세요."},
  "44": {"#ko": "비밀번호(암호화용):"},
  "45": {"#ko": "수익"},
  "46": {"#ko": "연결 안 됨"},
  "47": {"#ko": "제휴 링크 복사"},
  "48": {"#ko": "내 제휴 변경"},
  "49": {"#ko": "맞춤형 추천 수수료 설정"},
  "50": {"#ko": "기본 이메일 클라이언트를 통해 (해당 경우에) 잠재고객에게 통지 시도"}
}

languages['po']={
  "1": {"#po": "Mercados Descentralizados BitBay"},
  "2": {"#po": "Mercados Descentralizados BitBay"},
  "3": {"#po": "Conectar Metamask"},
  "4": {"#po": "Não conectado"},
  "5": {"#po": "Mercados"},
  "6": {"#po": "Ofertas"},
  "7": {"#po": "Contratos"},
  "8": {"#po": "Conta"},
  "9": {"#po": "Sobre"},
  "10": {"#po": "Bens"},
  "11": {"#po": "Serviços"},
  "12": {"#po": "Troca"},
  "13": {"#po": "Negociação P2P"},
  "14": {"#po": "Commodities"},
  "15": {"#po": "Mercados"},
  "16": {"#po": "Criar Contrato/Oferta"},
  "17": {"#po": "Pesquisar"},
  "18": {"#po": "Anterior"},
  "19": {"#po": "Próximo"},
  "20": {"#po": "Ordenar: Padrão"},
  "21": {"#po": "Ordenar: Melhor preço"},
  "22": {"#po": "Ordenar: Preço alto"},
  "23": {"#po": "Ofertas"},
  "24": {"#po": "Contratos"},
  "25": {"#po": "Conta"},
  "26": {"#po": "Por favor, conecte o Metamask"},
  "27": {"#po": "Depositar tokens"},
  "28": {"#po": "Retirar tokens"},
  "29": {"#po": "Informações de Contato (e-mail/signal/telegrama):"},
  "30": {"#po": "Registrar informações no meu endereço (contato/criptografia/opcional)"},
  "31": {"#po": "Limpar automaticamente contratos concluídos"},
  "32": {"#po": "Atualizar/restaurar contratos previamente limpos"},
  "33": {"#po": "Ofertas privadas expiram: "},
  "34": {"#po": "Nunca"},
  "35": {"#po": "Duas semanas"},
  "36": {"#po": "Um mês"},
  "37": {"#po": "Backup de dados do site/usuário"},
  "38": {"#po": "Carregar dados do site/usuário do arquivo"},
  "39": {"#po": "Usar o IPFS Pinata Gateway padrão"},
  "40": {"#po": "Sobre"},
  "41": {"#po": "Bem-vindo ao mundo dos contratos inquebráveis. Esses são contratos de garantia de duas partes (depósito duplo) que não podem ser quebrados e não requerem árbitros de terceiros. Ambos os usuários depositam um valor personalizável juntamente com um pagamento em uma conta conjunta. Se o negócio correr bem, ambos concordam com isso. Se uma das partes tentar fraudar a outra, o acordo eventualmente expira e se desfaz, de modo que ninguém ganha e o roubo não é lucrativo. Isso força os usuários a serem honestos e a cumprir seus acordos, pois ou ganham juntos ou perdem juntos."},
  "42": {"#po": "Os próprios mercados funcionam em cima de blockchains Solidity, como Ethereum e Polygon. As ofertas podem variar de bens, serviços, trocas e negociações P2P. Como esta página da web é totalmente de código aberto e funciona no lado do cliente, o usuário também pode baixar este código do GitHub e executá-lo localmente para uma segurança ainda maior. Esse protocolo, que foi pioneiro pela BitHalo em 2014, antecede o Ethereum e foi o primeiro contrato inteligente do mundo. Esta é uma interface baseada na web para mercados totalmente descentralizados."},
  "43": {"#po": "Para vender mercadorias, os usuários certamente desejarão considerar um serviço de envio direto ou um serviço que ofereça frete com desconto para competir com as taxas de envio normalmente encontradas nas grandes empresas. Para fazer isso, você deve se inscrever em uma conta de frete de terceiros, que deve permitir que você economize até 75% no frete em alguns casos. Os vendedores também podem cobrar dos compradores pelo frete enquanto estiverem em depósito e os compradores devem ter cuidado para garantir que o valor não exceda os depósitos ou que eles próprios comprem a etiqueta de envio. Os usuários devem tentar manter a comunicação entre si através do processo de depósito e é recomendado ter um backup de suas chaves para que ambas as partes estejam protegidas durante o depósito. Embora estes mercados possam ser moderados através de IA (como o webgpt) e moderação conduzida pela comunidade, os utilizadores são inteiramente responsáveis pelos riscos do que publicam e pelos seus próprios depósitos. Com isso em mente, é altamente recomendável não postar conteúdo ilegal no país em que você reside. Para negócios que envolvem dinheiro, os usuários devem fazer suas próprias diligências e seu próprio “conheça seu cliente”, se necessário. É do interesse de todos usar o depósito duplo de garantia para se livrar do engano no mundo do comércio e serviços internacionais. É uma vantagem quando os próprios usuários administram os contratos porque os árbitros não conseguem saber a veracidade de um acordo que decide injustamente e podem conspirar, causando grandes perdas e também incorrendo em custos maiores. Os usuários são forçados a trabalhar uns com os outros para alcançar um resultado desejável. Os usuários também são aqueles que hospedam as ofertas usando IPFS. Portanto, é uma boa prática executar seu próprio nó IPFS para arquivar os mercados. É recomendado que você registre suas informações de contato no blockchain. Isso garante que as contrapartes no contrato saibam como contatá-lo para qualquer dúvida sobre as negociações. O código pode ser executado localmente e também auditado visitando a página do github onde o código e o site estão hospedados. Este sistema não tem proprietário e é totalmente gratuito. No entanto, existe uma configuração que pode ser ativada para afiliados/referências que pode variar de 0 a 1%. Para incentivar os usuários a se envolverem com afiliados, a taxa será queimada se não for paga a um afiliado. Isso ajuda a comercializar o sistema, dando aos usuários uma maneira de ganhar. Um usuário dos mercados é automaticamente um afiliado se completar 10 negócios. Isso lhes permite usar os mercados gratuitamente se assim o desejarem (já que podem ser seus próprios afiliados) e permite que enviem usuários ao site por meio de um link de afiliado. A visita por meio de um link registra o afiliado nessa conta quando uma oferta é aceita e permite que ele se beneficie dessa indicação. Além disso, alguns vendedores podem oferecer uma taxa de referência mais atraente, o que deve permitir que os afiliados obtenham mais lucros por consentimento mútuo. Para obter mais informações sobre como o BitBay funciona, você pode visitar: "},
  "44": {"#po": "Senha(para criptografia):"},
  "45": {"#po": "Ganhe"},
  "46": {"#po": "Não conectado"},
  "47": {"#po": "Copiar link de afiliado"},
  "48": {"#po": "Alterar meu afiliado"},
  "49": {"#po": "Definir taxa de indicação personalizada"},
  "50": {"#po": "Tentativa de notificar prospects através do cliente de e-mail padrão (quando aplicável)"}
};

languages['ru'] = {
  "1": {"#ru": "Децентрализованные рынки BitBay"},
  "2": {"#ru": "Децентрализованные рынки BitBay"},
  "3": {"#ru": "Подключить Metamask"},
  "4": {"#ru": "Не подключено"},
  "5": {"#ru": "Рынки"},
  "6": {"#ru": "Предложения"},
  "7": {"#ru": "Контракты"},
  "8": {"#ru": "Аккаунт"},
  "9": {"#ru": "О нас"},
  "10": {"#ru": "Товары"},
  "11": {"#ru": "Услуги"},
  "12": {"#ru": "Бартер"},
  "13": {"#ru": "P2P Торговля"},
  "14": {"#ru": "Товары"},
  "15": {"#ru": "Рынки"},
  "16": {"#ru": "Создать Контракт/Предложение"},
  "17": {"#ru": "Поиск"},
  "18": {"#ru": "Предыдущий"},
  "19": {"#ru": "Следующий"},
  "20": {"#ru": "Сортировать: По умолчанию"},
  "21": {"#ru": "Сортировать: Лучшая цена"},
  "22": {"#ru": "Сортировать: Высокая цена"},
  "23": {"#ru": "Предложения"},
  "24": {"#ru": "Контракты"},
  "25": {"#ru": "Аккаунт"},
  "26": {"#ru": "Пожалуйста, подключите Metamask"},
  "27": {"#ru": "Депозит токенов"},
  "28": {"#ru": "Вывести токены"},
  "29": {"#ru": "Контактная информация (электронная почта/signal/телеграм):"},
  "30": {"#ru": "Зарегистрировать информацию на мой адрес(контакт/шифрование/необязательно)"},
  "31": {"#ru": "Автоматически очищать завершенные контракты"},
  "32": {"#ru": "Обновить/восстановить ранее очищенные контракты"},
  "33": {"#ru": "Срок действия частных предложений: "},
  "34": {"#ru": "Никогда"},
  "35": {"#ru": "Две недели"},
  "36": {"#ru": "Один месяц"},
  "37": {"#ru": "Резервное копирование кэша сайта/пользовательских данных"},
  "38": {"#ru": "Загрузить данные сайта/пользователя из файла"},
  "39": {"#ru": "Использовать стандартный IPFS Pinata Gateway"},
  "40": {"#ru": "О нас"},
  "41": {"#ru": "Добро пожаловать в мир нерушимых контрактов. Это двусторонние эскроу-контракты (двойной депозит), которые нельзя нарушить и не требуют арбитров от третьих лиц. Оба пользователи размещают настраиваемый депозит вместе с оплатой на общий счет. Если сделка проходит успешно, они оба ее подтверждают. Если одна из сторон пытается обмануть другую, сделка в конечном итоге истекает и разрушается, так что никто не выигрывает, и кража становится бесполезной. Это заставляет пользователей быть честными и соблюдать свои соглашения, поскольку они либо выигрывают вместе, либо проигрывают вместе."},
  "42": {"#ru": "Сами рынки работают на блокчейнах Solidity, таких как Ethereum и Polygon. Предложения могут варьироваться от товаров, услуг, бартера до P2P-торговли. Поскольку эта веб-страница полностью открытого исходного кода и работает на стороне клиента, пользователь также может загрузить этот код с GitHub и запустить его локально для еще большей безопасности. Этот протокол, который был создан BitHalo еще в 2014 году, предшествовал Ethereum и был первым в мире смарт-контрактом. Это веб-интерфейс для полностью децентрализованных рынков."},
  "43": {"#ru": "Для продажи товаров пользователи определенно захотят рассмотреть возможность прямой доставки или услуги, которая обеспечивает доставку со скидкой, чтобы конкурировать со тарифами на доставку, обычно встречающимися в крупных компаниях. Для этого вам следует зарегистрировать стороннюю учетную запись доставки, которая в некоторых случаях позволит вам сэкономить до 75% на доставке. Продавцы также могут взимать с покупателей плату за доставку, пока она находится на условном депонировании, и покупатели должны быть осторожны, чтобы убедиться, что сумма не превышает депозит, или что они сами покупают транспортную этикетку. Пользователям следует стараться поддерживать связь друг с другом в процессе условного депонирования, и рекомендуется иметь резервную копию ваших ключей, чтобы обе стороны были защищены во время депонирования. Хотя эти рынки могут модерироваться с помощью искусственного интеллекта (например, webgpt) и модерации, управляемой сообществом, пользователи несут полную ответственность за риски того, что они публикуют, и за свои собственные депозиты. Имея это в виду, настоятельно рекомендуется не публиковать контент, который является незаконным в стране вашего проживания. Для сделок, в которых используются наличные, пользователи должны провести собственную комплексную проверку и, при необходимости, «знать своего клиента». В интересах каждого использовать двойное условное депонирование, чтобы избавиться от обмана в мире международной торговли и услуг. Это преимущество, когда пользователи сами администрируют контракты, поскольку арбитры не могут знать правду о несправедливом решении сделки и могут вступить в сговор, что приведет к большим потерям, а также повлечет за собой более высокие затраты. Пользователи вынуждены работать друг с другом для достижения желаемого результата. Пользователи также размещают предложения с использованием IPFS. Поэтому хорошей практикой является запуск собственного узла IPFS для архивирования рынков. Рекомендуется зарегистрировать свою контактную информацию в блокчейне. Это дает гарантию того, что контрагенты по договору знают, как с вами связаться по любым вопросам, связанным с переговорами. Код можно запускать локально, а также его можно проверить, посетив страницу github, где размещен код и веб-сайт. Эта система не имеет владельца и полностью бесплатна для использования. Однако есть настройка, которую можно активировать для партнеров/рефералов, которая может варьироваться от 0 до 1%. Чтобы побудить пользователей взаимодействовать с партнерами, комиссия сгорает, если она не выплачивается партнеру. Это помогает продвигать систему, предоставляя пользователям возможность зарабатывать. Пользователь рынков автоматически становится партнером, если он совершает 10 сделок. Это позволяет им использовать рынки бесплатно, если они захотят (поскольку они могут быть собственными партнерами), а также отправлять пользователей на веб-сайт через партнерскую ссылку. Посещение ссылки регистрирует партнера в этой учетной записи, когда сделка принята, и позволяет ему получать выгоду от этого реферала. Кроме того, некоторые продавцы могут предлагать более привлекательную комиссию за рефералов, которая должна позволить партнерам получать больше прибыли по взаимному согласию. Для получения дополнительной информации о том, как работает BitBay, вы можете посетить: "},
  "44": {"#ru": "Пароль (для шифрования):"},
  "45": {"#ru": "Заработать"},
  "46": {"#ru": "Нет соединения"},
  "47": {"#ru": "Копировать партнерскую ссылку"},
  "48": {"#ru": "Изменить мой партнер"},
  "49": {"#ru": "Установить свою комиссию за рефералов"},
  "50": {"#ru": "Попытка уведомления потенциальных клиентов через стандартного почтового клиента (по возможности)"}
}

languages['sp'] = {
  "1": {"#sp": "Mercados Descentralizados BitBay"},
  "2": {"#sp": "Mercados Descentralizados BitBay"},
  "3": {"#sp": "Conectar Metamask"},
  "4": {"#sp": "No conectado"},
  "5": {"#sp": "Mercados"},
  "6": {"#sp": "Ofertas"},
  "7": {"#sp": "Contratos"},
  "8": {"#sp": "Cuenta"},
  "9": {"#sp": "Acerca de nosotros"},
  "10": {"#sp": "Bienes"},
  "11": {"#sp": "Servicios"},
  "12": {"#sp": "Trueque"},
  "13": {"#sp": "Trading P2P"},
  "14": {"#sp": "Productos"},
  "15": {"#sp": "Mercados"},
  "16": {"#sp": "Crear Contrato/Oferta"},
  "17": {"#sp": "Buscar"},
  "18": {"#sp": "Anterior"},
  "19": {"#sp": "Siguiente"},
  "20": {"#sp": "Ordenar: Por defecto"},
  "21": {"#sp": "Ordenar: Mejor precio"},
  "22": {"#sp": "Ordenar: Precio alto"},
  "23": {"#sp": "Ofertas"},
  "24": {"#sp": "Contratos"},
  "25": {"#sp": "Cuenta"},
  "26": {"#sp": "Por favor, conecte Metamask"},
  "27": {"#sp": "Depositar tokens"},
  "28": {"#sp": "Retirar tokens"},
  "29": {"#sp": "Información de contacto (correo electrónico/signal/telegrama):"},
  "30": {"#sp": "Registrar información en mi dirección (contacto/cifrado/opcional)"},
  "31": {"#sp": "Borrar automáticamente contratos completados"},
  "32": {"#sp": "Actualizar/restaurar contratos previamente borrados"},
  "33": {"#sp": "Vencimiento de ofertas privadas: "},
  "34": {"#sp": "Nunca"},
  "35": {"#sp": "Dos semanas"},
  "36": {"#sp": "Un mes"},
  "37": {"#sp": "Copia de seguridad de datos del sitio/usuario"},
  "38": {"#sp": "Cargar datos del sitio/usuario desde archivo"},
  "39": {"#sp": "Usar la puerta de enlace IPFS Pinata predeterminada"},
  "40": {"#sp": "Acerca de nosotros"},
  "41": {"#sp": "Bienvenido al mundo de los contratos irrompibles. Estos son contratos de custodia entre dos partes (doble depósito) que no pueden romperse y no requieren árbitros de terceros. Ambos usuarios colocan un depósito personalizable junto con un pago en una cuenta conjunta. Si el trato va bien, ambos lo confirman. Si una de las partes intenta estafar a la otra, el trato eventualmente expirará y fracasará, de modo que nadie gana y el robo no es rentable. Esto obliga a los usuarios a ser honestos y cumplir con sus acuerdos, ya que o ganan juntos o pierden juntos."},
  "42": {"#sp": "Los propios mercados se ejecutan en cadenas Solidity como Ethereum y Polygon. Las ofertas pueden variar desde bienes, servicios, trueque hasta trading P2P. Dado que esta página web es de código abierto y se ejecuta en el lado del cliente, el usuario también puede descargar este código desde GitHub y ejecutarlo localmente para una mayor seguridad. Este protocolo, que fue pionero de BitHalo en 2014, precedió a Ethereum y fue el primer contrato inteligente del mundo. Esta es una interfaz web para mercados totalmente descentralizados."},
  "43": {"#sp": "Para vender productos, los usuarios definitivamente querrán considerar un servicio de envío directo o un servicio que ofrezca envío con descuento para competir con las tarifas de envío que normalmente se encuentran en las principales empresas. Para hacer esto, debe registrarse para obtener una cuenta de envío de terceros que debería permitirle ahorrar hasta un 75% en el envío en algunos casos. Los vendedores también pueden cobrar a los compradores por el envío mientras están en depósito en garantía y los compradores deben tener cuidado de asegurarse de que el monto no exceda los depósitos o de que ellos mismos compren la etiqueta de envío. Los usuarios deben intentar mantenerse en comunicación entre sí durante el proceso de depósito en garantía y se recomienda tener una copia de seguridad de sus claves para que ambas partes estén protegidas durante el depósito en garantía. Aunque estos mercados podrían moderarse mediante IA (como webgpt) y moderación impulsada por la comunidad, los usuarios son totalmente responsables de los riesgos de lo que publican y de sus propios depósitos en garantía. Teniendo esto en cuenta, se recomienda encarecidamente no publicar contenido que sea ilegal en el país donde reside. Para acuerdos que involucran efectivo, los usuarios deben hacer su propia diligencia debida y su propio 'conozca a su cliente' si es necesario. Lo mejor para todos es utilizar el depósito en garantía doble para deshacerse del engaño en el mundo del comercio y los servicios internacionales. Es una ventaja que los usuarios administren los contratos ellos mismos porque los árbitros no pueden conocer la verdad de un acuerdo que falla injustamente y pueden confabularse causando grandes pérdidas y también incurriendo en un mayor costo. Los usuarios se ven obligados a trabajar entre sí para lograr un resultado deseable. Los usuarios también son quienes alojan las ofertas utilizando IPFS. Por lo tanto, es una buena práctica ejecutar su propio nodo IPFS para archivar los mercados. Se recomienda que registre su información de contacto en blockchain. Esto garantiza que las contrapartes del contrato sepan cómo ponerse en contacto con usted para cualquier pregunta sobre las negociaciones. El código se puede ejecutar localmente y también se puede auditar visitando la página de GitHub donde están alojados el código y el sitio web. Este sistema no tiene propietario y su uso es totalmente gratuito. Sin embargo, hay una configuración que se puede activar para afiliados/referidos que puede oscilar entre 0 y 1%. Para alentar a los usuarios a interactuar con afiliados, la tarifa se gasta si no se paga a un afiliado. Esto ayuda a comercializar el sistema al brindarles a los usuarios una forma de ganar dinero. Un usuario de los mercados se convierte automáticamente en afiliado si completa 10 transacciones. Eso les permite utilizar los mercados de forma gratuita si así lo desean (ya que pueden ser su propio afiliado) y les permite enviar usuarios al sitio web a través de un enlace de afiliado. La visita a través de un enlace registra al afiliado en esa cuenta cuando se acepta una oferta y le permite beneficiarse de esa referencia. Además, algunos vendedores pueden ofrecer una tarifa de referencia más atractiva que debería permitir a los afiliados obtener más ganancias de mutuo acuerdo. Para obtener más información sobre cómo funciona BitBay, puede visitar: "},
  "44": {"#sp": "Contraseña (para cifrado):"},
  "45": {"#sp": "Ganar"},
  "46": {"#sp": "No conectado"},
  "47": {"#sp": "Copiar enlace de afiliado"},
  "48": {"#sp": "Cambiar mi afiliado"},
  "49": {"#sp": "Establecer tarifa de referencia personalizada"},
  "50": {"#sp": "Intento de notificar a los posibles clientes a través del cliente de correo electrónico predeterminado (cuando sea aplicable)"}
};
