var langOptions = ['Arabic','Chinese','English','French','German','Italian','Japanese','Korean','Portuguese','Russian','Spanish'];
var languages={}
languages['ar']={
  "1": {"#ar": "أسواق بيت باي اللامركزية"},
  "2": {"#ar": "أسواق بيت باي اللامركزية"},
  "3": {"#ar": "اتصل بـ ميتاماسك"},
  "4": {"#ar": "غير متصل"},
  "5": {"#ar": "الأسواق"},
  "6": {"#ar": "العروض"},
  "7": {"#ar": "العقود"},
  "8": {"#ar": "الحساب"},
  "9": {"#ar": "حول"},
  "10": {"#ar": "السلع"},
  "11": {"#ar": "الخدمات"},
  "12": {"#ar": "التبادل"},
  "13": {"#ar": "تداول نقطي إلى نقطي"},
  "14": {"#ar": "السلع"},
  "15": {"#ar": "الأسواق"},
  "16": {"#ar": "إنشاء عقد/عرض"},
  "17": {"#ar": "البحث"},
  "18": {"#ar": "السابق"},
  "19": {"#ar": "التالي"},
  "20": {"#ar": "الترتيب: الافتراضي"},
  "21": {"#ar": "الترتيب: أفضل سعر"},
  "22": {"#ar": "الترتيب: سعر عالي"},
  "23": {"#ar": "العروض"},
  "24": {"#ar": "العقود"},
  "25": {"#ar": "الحساب"},
  "26": {"#ar": "الرجاء الاتصال بميتاماسك"},
  "27": {"#ar": "إيداع الرموز"},
  "28": {"#ar": "سحب الرموز"},
  "29": {"#ar": "معلومات الاتصال (البريد الإلكتروني/سيجنال/تليجرام):"},
  "30": {"#ar": "سجّل معلومات الاتصال بعنواني (اختياري)"},
  "31": {"#ar": "مسح العقود المكتملة تلقائيًا"},
  "32": {"#ar": "تحديث/استعادة العقود المحذوفة مسبقًا"},
  "33": {"#ar": "تنتهي العروض الخاصة: "},
  "34": {"#ar": "أبدًا"},
  "35": {"#ar": "أسبوعين"},
  "36": {"#ar": "شهر"},
  "37": {"#ar": "نسخ بيانات الموقع/المستخدم مؤقتًا"},
  "38": {"#ar": "تحميل بيانات الموقع/المستخدم من ملف"},
  "39": {"#ar": "استخدام بوابة IPFS الافتراضية لـ Pinata"},
  "40": {"#ar": "حول"},
  "41": {"#ar": "مرحبًا بك في عالم العقود القوية. هذه هي عقود الضمان ذات الطرفين (إيداع مزدوج) التي لا يمكن تحطيمها ولا تتطلب وسيطًا ثالثًا. يضع الطرفان إيداعًا قابلا للتخصيص جنبًا إلى جنب مع دفعة في حساب مشترك. إذا تمت الصفقة بنجاح، يوقع كل منهما عليها. إذا حاول أحد الأطراف الاحتيال على الآخر، ستنتهي الصفقة في النهاية وتنفجر، مما يجعل من الصعب الفوز بأي طرف ويصبح السرقة غير مربحة. هذا يجبر المستخدمين على أن يكونوا صادقين ويتبعوا التزاماتهم حيث يفوزون معًا أو يخسرون معًا."},
  "42": {"#ar": "تعمل الأسواق بشكل ذاتي على سلاسل Solidity مثل إيثيريوم وبوليغون. يمكن أن تتنوع العروض بين السلع والخدمات والتبادل وتداول نقطي إلى نقطي. نظرًا لأن هذه الصفحة واجهة ويب مفتوحة المصدر بالكامل وتعمل على جانب العميل، يمكن للمستخدم تنزيل هذا الكود من Github وتشغيله محليًا لتحقيق أمان أكبر. تمت تقنين هذا البروتوكول الذي قامت به بيت هالو لأول مرة في عام 2014 قبل إيثيريوم وكان أول عقود ذكية في العالم. هذه واجهة ويب للأسواق المفcentralة بالكامل."},
  "43": {"#ar": "بالنسبة لبيع السلع، يجب على المستخدمين التفكير في خدمة الشحن المباشر أو خدمة توفير تخفيضات في تكاليف الشحن للتنافس مع أسعار الشحن التي تجدها عادة في الشركات الكبرى. للقيام بذلك، يجب عليك الاشتراك في حساب شحن منفصل يجب أن يسمح لك بتوفير أكثر من 75٪ في تكاليف الشحن. قد يفرض البائعون أيضًا رسومًا على المشترين للشحن أثناء التخزين الآمن ويجب على المشترين أن يكونوا حذرين للتأكد من أن المبلغ لا يتجاوز الودائع أو أن يشتروا تسمية الشحن بأنفسهم. يجب على المستخدمين البقاء في اتصال مع بعضهم البعض خلال عملية التخزين الآمن ويُنصح بأن يكون لديك نسخة احتياطية من مفاتيحك حتى يتم حماية الطرفين أثناء التخزين الآمن. على الرغم من أن هذه الأسواق يمكن أن تُدير من خلال الذكاء الاصطناعي (مثل webgpt) والتسويق الذي يقوده المجتمع، يتحمل المستخدمون المسؤولية الكاملة عن المخاطر المترتبة على ما يقومون بنشره وعلى تخزينهم الآمن. بالنسبة للصفقات التي تشمل النقد، يجب على المستخدمين إجراء فحص دقيق لأعمالهم والتحقق من الهوية إذا لزم الأمر. إن استخدام التخزين الآمن بإيداع مزدوج هو ميزة تزيل الخداع في عالم التجارة والخدمات الدولية. إنه ميزة عندما يدير المستخدمون عقودهم بأنفسهم لأن الحكام لا يمكنهم معرفة حقيقة صفقة يحكمون بشكل غير عادل ويمكنهم التواطؤ مسببين خسائر كبيرة ويتحملون تكلفة أكبر. يتم إجبار المستخدمين على العمل معًا لتحقيق نتيجة مرغوبة. المستخدمون هم أيضًا الذين يستضيفون العروض باستخدام IPFS. لذا فإن تشغيل العقد الخاصة بك هو ممارسة جيدة لتشغيل عقد السوق. يُنصح بتسجيل معلومات الاتصال الخاصة بك على سلسلة الكتل. يجعل ذلك من المؤكد أن الأطراف المعنية بالعقد يعرفون كيفية الاتصال بك لأي أسئلة حول التفاوض. يمكن تشغيل الكود محليًا ويمكن أيضًا فحصه عبر زيارة صفحة GitHub حيث يتم استضافة الكود والموقع. لا تأخذ BitBay أي رسوم للتخزين الآمن. هذا النظام مجاني تمامًا للاستخدام. لمزيد من المعلومات حول كيفية عمل كل هذا، يمكنك زيارة: "}
};


languages['ch']={
  "1":{"#ch":"BitBay 去中心化市场"},
  "2":{"#ch":"BitBay 去中心化市场"},
  "3":{"#ch":"连接 Metamask"},
  "4":{"#ch":"未连接"},
  "5":{"#ch":"市场" },
  "6":{"#ch":"报价"},
  "7":{"#ch":"合同"},
  "8":{"#ch":"账户"},
  "9":{"#ch":"关于"},
  "10":{"#ch":"商品"},
  "11":{"#ch":"服务"},
  "12":{"#ch":"易货贸易"},
  "13":{"#ch":" P2P交易"},
  "14":{"#ch":"商品"},
  "15":{"#ch":"市场"},
  "16":{"#ch":"创建合同/报价"},
  "17":{"#ch":"搜索"},
  "18":{"#ch":"上一页 "},
  "19":{"#ch":"下一步"},
  "20":{"#ch":"排序：默认"},
  "21":{"#ch":"排序：最优惠价格"},
  "22":{"#ch":"排序：最高价格"},
  "23":{"#ch" :"优惠"},
  "24":{"#ch":"合同"},
  "25":{"#ch":"账户"},
  "26":{"#ch":"请连接元掩码"},
  "27":{"#ch":"充值代币"},
  "28":{"#ch":" 提取代币"},
  "29":{"#ch":"联系信息(电子邮件/信号/电报):"},
  "30":{"#ch":"注册联系人 信息发送到我的地址（可选）"},
  "31":{"#ch":"自动清除已完成的合同"},
  "32":{"#ch":"刷新/恢复 之前清算的合同"},
  "33":{"#ch":"私人优惠到期:"},
  "34":{"#ch":"永不"},
  "35" :{"#ch":"两周"},
  "36":{"#ch":"一个月"},
  "37":{"#ch" :"备份缓存的站点/用户数据"},
  "38":{"#ch":"从文件加载站点/用户数据"},
  "39":{"#ch": "使用默认的 IPFS Pinata 网关"},
  "40":{"#ch":"关于"},
  "41":{"#ch":"欢迎来到牢不可破的合约世界 。 这些是两方托管（双倍存款）合约，无法被破坏，并且不需要第三方仲裁者。 两个用户都将可定制的存款和付款存入联名账户。 如果交易进展顺利，双方都会签字。 如果一方试图欺骗另一方，交易最终将到期并破裂，导致没有人获胜，盗窃也无利可图。 这迫使用户诚实并遵守协议，因为他们要么一起赢，要么一起输。"},
  "42":{"#ch":"市场本身在 Solidity 链之上运行 例如以太坊和Polygon。 优惠范围包括商品、服务、易货贸易和点对点交易。 由于该网页完全开源并在客户端运行，因此用户还可以从 github 下载此代码并在本地运行，以提高安全性。 该协议由 BitHalo 于 2014 年首创，早于以太坊，是世界上第一个智能合约。 这是一个基于网络的界面，适用于完全去中心化的市场。"},
  "43":{"#ch":"对于销售商品，用户肯定会考虑直接送货服务或提供折扣送货的服务 与大公司通常的运费竞争。 为此，您应该注册一个第三方运输帐户，这应该可以让您节省超过 75% 的运费。 卖家还可能在托管期间向买家收取运费，买家应注意确保金额不超过押金，或者他们自己购买运输标签。 用户应尝试通过托管过程保持彼此通信，建议备份密钥，以便双方在托管期间都受到保护。 尽管这些市场可以通过人工智能（例如 webgpt）和社区驱动的审核来进行审核，但用户要对他们发布的内容和自己的托管承担全部责任。 考虑到这一点，强烈建议不要发布在您居住的国家/地区非法的内容。 对于涉及现金的交易，用户应自行尽职调查，并在需要时“了解您的客户”。 使用双重存款托管来消除国际商业和服务领域的欺骗符合每个人的最佳利益。 用户自己管理合约是一个优势，因为仲裁者无法知道不公平裁决的交易真相，并且可能串通造成巨大损失，同时也会产生更大成本。 用户被迫相互合作才能获得理想的结果。 用户也是使用 IPFS 托管商品的人。 因此，运行自己的 IPFS 节点来存档市场是一个很好的做法。 建议您将联系信息注册到区块链上。 这可以保证合同中的对方知道如何与您联系以解决有关谈判的任何问题。 代码可以在本地运行，也可以通过访问托管代码和网站的 github 页面进行审核。 BitBay 不收取任何托管费用。 该系统完全免费使用。 有关这一切如何运作的更多信息，您可以访问："}
};

languages['en']={
  "1":{"#en":"BitBay Decentralized Markets"},
  "2":{"#en":"BitBay Decentralized Markets"},
  "3":{"#en":"Connect Metamask"},
  "4":{"#en":"Not connected"},
  "5":{"#en":"Markets"},
  "6":{"#en":"Offers"},
  "7":{"#en":"Contracts"},
  "8":{"#en":"Account"},
  "9":{"#en":"About"},
  "10":{"#en":"Goods"},
  "11":{"#en":"Services"},
  "12":{"#en":"Barter"},
  "13":{"#en":"P2P Trading"},
  "14":{"#en":"Commodities"},
  "15":{"#en":"Markets"},
  "16":{"#en":"Create Contract/Offer"},
  "17":{"#en":"Search"},
  "18":{"#en":"Previous"},
  "19":{"#en":"Next"},
  "20":{"#en":"Sort: Default"},
  "21":{"#en":"Sort: Best price"},
  "22":{"#en":"Sort: High price"},
  "23":{"#en":"Offers"},
  "24":{"#en":"Contracts"},
  "25":{"#en":"Account"},
  "26":{"#en":"Please connect metamask"},
  "27":{"#en":"Deposit tokens"},
  "28":{"#en":"Withdraw tokens"},
  "29":{"#en":"Contact Information(email/signal/telegram):"},
  "30":{"#en":"Register contact information to my address(optional)"},
  "31":{"#en":"Automatically clear completed contracts"},
  "32":{"#en":"Refresh/restore previously cleared contracts"},
  "33":{"#en":"Private offers expire: "},
  "34":{"#en":"Never"},
  "35":{"#en":"Two weeks"},
  "36":{"#en":"One month"},
  "37":{"#en":"Backup cached site/user data"},
  "38":{"#en":"Load site/user data from file"},
  "39":{"#en":"Use default IPFS Pinata Gateway"},
  "40":{"#en":"About"},
  "41":{"#en":"Welcome to the world of unbreakable contracts. These are two party escrow(double deposit) contracts that cannot be broken and require no 3rd party arbiters. Both users place a customizable deposit along with a payment into a joint account. If the deal goes well they both sign off on it. If one party tries to defraud the other the deal will eventually expire and blow up making it so that nobody wins and theft is profitless. This forces the users to be honest and follow through with their agreements since they either win together or they lose together."},
  "42":{"#en":"The markets themselves run on top of Solidity chains such as Ethereum and Polygon. Offers can range from goods, services, barter and p2p trading. Since this webpage is fully open source and runs on the client side, the user can also download this code from github and run it locally for even greater security. This protocol which was pioneered by BitHalo back in 2014 predated Ethereum and was the worlds first smart contracts. This is a web based interface for fully decentralized markets."},
  "43":{"#en":"For selling goods, users will definitely want to consider a drop shipping service or a service that provides discount shipping to compete with the shipping rates typically found in major companies. To do this, you should sign up for a 3rd party shipping account which should allow you to save well over 75% in shipping. Sellers may also charge buyers for shipping while in escrow and buyers should be careful to make sure the amount doesn't exceed the deposits or that they buy the shipping label themselves. Users should try to keep in communication with each other through the escrow process and it's recommended to have a backup of your keys so both parties are protected during escrow. Although these markets could be moderated through AI(such as webgpt) and community driven moderation, users are entirely responsible for the risks of what they post and for their own escrows. With that in mind, it's strongly recommended to not post content that is illegal in the country you reside. For deals that involve cash users should do their own due dilligence and their own \"know your customer\" if needed. It's in everyones best interest to use double deposit escrow to get rid of deception in the world of international commerce and services. It is an advantage when users administrate contracts themselves because arbiters are unable to know the truth of a deal ruling unfairly and can collude causing great losses and they also incur a greater cost. Users are forced to work with each other to achieve a desirable outcome. Users are also the ones who host the offers using IPFS. So it's good practice to run your own IPFS node to archive the markets. It's recommended that you register your contact information to the blockchain. This makes it guaranteed that counter-parties in the contract know how to contact you for any questions about the negotiations. The code may be run locally and can also be audited by visiting the github page where the code and website are hosted. BitBay does not take any fees for the escrows. This system is entirely free to use. For more information on how all of this works you may visit: "}
};

languages['fr']={
  "1": {"#fr": "Marchés décentralisés BitBay"},
  "2": {"#fr": "Marchés décentralisés BitBay"},
  "3": {"#fr": "Connecter Metamask"},
  "4": {"#fr": "Non connecté"},
  "5": {"#fr": "Marchés"},
  "6": {"#fr": "Offres"},
  "7": {"#fr": "Contrats"},
  "8": {"#fr": "Compte"},
  "9": {"#fr": "À propos"},
  "10": {"#fr": "Biens"},
  "11": {"#fr": "Services"},
  "12": {"#fr": "Troquer"},
  "13": {"#fr": "Trading P2P"},
  "14": {"#fr": "Biens"},
  "15": {"#fr": "Marchés"},
  "16": {"#fr": "Créer un contrat/offre"},
  "17": {"#fr": "Rechercher"},
  "18": {"#fr": "Précédent"},
  "19": {"#fr": "Suivant"},
  "20": {"#fr": "Trier : Par défaut"},
  "21": {"#fr": "Trier : Meilleur prix"},
  "22": {"#fr": "Trier : Prix élevé"},
  "23": {"#fr": "Offres"},
  "24": {"#fr": "Contrats"},
  "25": {"#fr": "Compte"},
  "26": {"#fr": "Veuillez connecter Metamask"},
  "27": {"#fr": "Déposer des jetons"},
  "28": {"#fr": "Retirer des jetons"},
  "29": {"#fr": "Informations de contact (e-mail/signal/télégramme) :"},
  "30": {"#fr": "Enregistrer les informations de contact à mon adresse (facultatif)"},
  "31": {"#fr": "Effacer automatiquement les contrats terminés"},
  "32": {"#fr": "Actualiser/restaurer les contrats préalablement effacés"},
  "33": {"#fr": "Les offres privées expirent : "},
  "34": {"#fr": "Jamais"},
  "35": {"#fr": "Deux semaines"},
  "36": {"#fr": "Un mois"},
  "37": {"#fr": "Sauvegarder les données temporaires du site/de l'utilisateur"},
  "38": {"#fr": "Charger les données du site/de l'utilisateur à partir d'un fichier"},
  "39": {"#fr": "Utiliser la passerelle IPFS par défaut de Pinata"},
  "40": {"#fr": "À propos"},
  "41": {"#fr": "Bienvenue dans le monde des contrats incassables. Ce sont des contrats d'entiercement à deux parties (double dépôt) qui ne peuvent pas être rompus et ne nécessitent aucun arbitre tiers. Les deux utilisateurs placent un dépôt personnalisable ainsi qu'un paiement dans un compte commun. Si l'affaire se déroule bien, ils signent tous les deux. Si l'une des parties tente de tromper l'autre, l'affaire expirera finalement et éclatera, de sorte que personne ne gagne et le vol est sans profit. Cela force les utilisateurs à être honnêtes et à respecter leurs accords, car ils gagnent ensemble ou perdent ensemble."},
  "42": {"#fr": "Les marchés eux-mêmes fonctionnent sur des chaînes Solidity telles qu'Ethereum et Polygon. Les offres peuvent varier des biens, des services, du troc et du trading P2P. Puisque cette page web est entièrement open source et s'exécute côté client, l'utilisateur peut également télécharger ce code depuis GitHub et l'exécuter localement pour une sécurité accrue. Ce protocole, pionnier de BitHalo en 2014, a précédé Ethereum et était le tout premier contrat intelligent au monde. Il s'agit d'une interface Web pour des marchés entièrement décentralisés."},
  "43": {"#fr": "Pour vendre des biens, les utilisateurs voudront certainement envisager un service d'expédition directe ou un service offrant des réductions sur les frais d'expédition pour rivaliser avec les tarifs d'expédition généralement pratiqués par les grandes entreprises. Pour ce faire, vous devriez vous inscrire à un compte d'expédition tiers qui devrait vous permettre d'économiser bien plus de 75% sur les frais d'expédition. Les vendeurs peuvent également facturer aux acheteurs des frais d'expédition pendant l'entiercement, et les acheteurs doivent être prudents pour s'assurer que le montant n'excède pas les dépôts ou qu'ils achètent eux-mêmes l'étiquette d'expédition. Les utilisateurs devraient essayer de rester en communication les uns avec les autres tout au long du processus d'entiercement et il est recommandé de disposer d'une sauvegarde de vos clés pour que les deux parties soient protégées pendant l'entiercement. Bien que ces marchés pourraient être modérés par l'IA (comme webgpt) et une modération dirigée par la communauté, les utilisateurs sont entièrement responsables des risques liés à ce qu'ils publient et à leurs propres entiercements. Dans cette optique, il est fortement recommandé de ne pas publier de contenu illégal dans le pays où vous résidez. Pour les transactions en espèces, les utilisateurs doivent faire leurs propres due diligence et leur propre 'know your customer' si nécessaire. Il est dans l'intérêt de tous d'utiliser l'entiercement à double dépôt pour se débarrasser de la tromperie dans le monde du commerce et des services internationaux. C'est un avantage lorsque les utilisateurs administrent eux-mêmes les contrats car les arbitres ne peuvent pas connaître la vérité d'une affaire jugée de manière injuste et peuvent conspirer causant de grandes pertes et ils supportent également un coût plus élevé. Les utilisateurs sont obligés de travailler ensemble pour obtenir un résultat souhaitable. Les utilisateurs sont également ceux qui hébergent les offres en utilisant IPFS. Il est donc bon de pratiquer l'exécution de votre propre nœud IPFS pour archiver les marchés. Il est recommandé de vous enregistrer sur la blockchain avec vos informations de contact. Cela garantit que les contreparties dans le contrat savent comment vous contacter pour toute question sur les négociations. Le code peut être exécuté localement et peut également être audité en visitant la page GitHub où le code et le site sont hébergés. BitBay ne prend aucuns frais pour les entiercements. Ce système est entièrement gratuit. Pour plus d'informations sur le fonctionnement de tout cela, vous pouvez visiter : "}
};

languages['ge']={
  "1": {"#ge": "BitBay Dezentralisierte Märkte"},
  "2": {"#ge": "BitBay Dezentralisierte Märkte"},
  "3": {"#ge": "Metamask verbinden"},
  "4": {"#ge": "Nicht verbunden"},
  "5": {"#ge": "Märkte"},
  "6": {"#ge": "Angebote"},
  "7": {"#ge": "Verträge"},
  "8": {"#ge": "Konto"},
  "9": {"#ge": "Über uns"},
  "10": {"#ge": "Waren"},
  "11": {"#ge": "Dienstleistungen"},
  "12": {"#ge": "Tauschhandel"},
  "13": {"#ge": "P2P-Handel"},
  "14": {"#ge": "Güter"},
  "15": {"#ge": "Märkte"},
  "16": {"#ge": "Vertrag/Angebot erstellen"},
  "17": {"#ge": "Suchen"},
  "18": {"#ge": "Vorherige"},
  "19": {"#ge": "Nächste"},
  "20": {"#ge": "Sortieren: Standard"},
  "21": {"#ge": "Sortieren: Bester Preis"},
  "22": {"#ge": "Sortieren: Hoher Preis"},
  "23": {"#ge": "Angebote"},
  "24": {"#ge": "Verträge"},
  "25": {"#ge": "Konto"},
  "26": {"#ge": "Bitte Metamask verbinden"},
  "27": {"#ge": "Token einzahlen"},
  "28": {"#ge": "Token abheben"},
  "29": {"#ge": "Kontaktinformationen (E-Mail/Signal/Telegramm):"},
  "30": {"#ge": "Kontaktinformationen an meine Adresse registrieren (optional)"},
  "31": {"#ge": "Abgeschlossene Verträge automatisch löschen"},
  "32": {"#ge": "Zuvor gelöschte Verträge aktualisieren/wiederherstellen"},
  "33": {"#ge": "Private Angebote laufen ab: "},
  "34": {"#ge": "Nie"},
  "35": {"#ge": "Zwei Wochen"},
  "36": {"#ge": "Ein Monat"},
  "37": {"#ge": "Gespeicherte Website-/Benutzerdaten sichern"},
  "38": {"#ge": "Website-/Benutzerdaten aus Datei laden"},
  "39": {"#ge": "Standard-IPFS-Pinata-Gateway verwenden"},
  "40": {"#ge": "Über uns"},
  "41": {"#ge": "Willkommen in der Welt der unzerbrechlichen Verträge. Dies sind Zweiparteien-Escrow(Doppeldatenträger)-Verträge, die nicht gebrochen werden können und keine Schiedsrichter von Dritten erfordern. Beide Benutzer legen eine anpassbare Kaution zusammen mit einer Zahlung auf ein gemeinsames Konto. Wenn die Transaktion gut verläuft, unterzeichnen beide. Wenn eine Partei versucht, die andere zu betrügen, wird die Transaktion schließlich ablaufen und scheitern, sodass niemand gewinnt und Diebstahl nutzlos ist. Dies zwingt die Benutzer, ehrlich zu sein und ihre Vereinbarungen einzuhalten, da sie entweder gemeinsam gewinnen oder gemeinsam verlieren."},
  "42": {"#ge": "Die Märkte selbst laufen auf Solidity-Ketten wie Ethereum und Polygon. Angebote können von Waren, Dienstleistungen, Tauschhandel bis hin zu P2P-Handel reichen. Da diese Webseite vollständig Open Source ist und auf der Client-Seite läuft, kann der Benutzer diesen Code auch von GitHub herunterladen und lokal ausführen, um noch mehr Sicherheit zu gewährleisten. Dieses Protokoll, das von BitHalo bereits 2014 entwickelt wurde, ging Ethereum voraus und war der weltweit erste intelligente Vertrag. Dies ist eine webbasierte Benutzeroberfläche für vollständig dezentralisierte Märkte."},
  "43": {"#ge": "Beim Verkauf von Waren sollten Benutzer auf jeden Fall einen Dropshipping-Service oder einen Service in Betracht ziehen, der einen Rabatt auf den Versand bietet, um mit den Versandkosten konkurrieren zu können, die normalerweise bei großen Unternehmen anfallen. Um dies zu erreichen, sollten Sie sich bei einem Drittanbieter-Versandkonto anmelden, das Ihnen ermöglichen sollte, weit über 75% der Versandkosten zu sparen. Verkäufer können Käufern auch Versandkosten während des Treuhandverfahrens in Rechnung stellen, und Käufer sollten darauf achten, dass der Betrag nicht die Einlagen übersteigt oder dass sie selbst das Versandetikett kaufen. Benutzer sollten versuchen, während des Treuhandverfahrens in Kontakt zu bleiben, und es wird empfohlen, eine Sicherung Ihrer Schlüssel zu haben, damit beide Parteien während des Treuhandverfahrens geschützt sind. Obwohl diese Märkte durch KI (wie webgpt) und gemeinschaftliche Moderation moderiert werden könnten, sind Benutzer vollständig für die Risiken dessen verantwortlich, was sie veröffentlichen, und für ihre eigenen Treuhandverfahren. In diesem Sinne wird dringend empfohlen, keinen Inhalt zu veröffentlichen, der im Land Ihres Wohnsitzes illegal ist. Für Geschäfte, die Bargeld beinhalten, sollten Benutzer ihre eigene Sorgfalt walten lassen und bei Bedarf ihr eigenes 'Know Your Customer' durchführen. Es ist im Interesse aller, das Treuhandverfahren mit doppeltem Einzahlungsbetrag zu verwenden, um Täuschung in der Welt des internationalen Handels und der Dienstleistungen zu beseitigen. Es ist von Vorteil, wenn Benutzer selbst Verträge verwalten, da Schiedsrichter nicht in der Lage sind, die Wahrheit einer Entscheidung zu kennen, die unfair ist, und Kollusionen verursachen große Verluste und verursachen auch höhere Kosten. Benutzer sind gezwungen, zusammenzuarbeiten, um ein wünschenswertes Ergebnis zu erzielen. Benutzer sind auch diejenigen, die die Angebote über IPFS hosten. Daher ist es ratsam, Ihren eigenen IPFS-Node zu betreiben, um die Märkte zu archivieren. Es wird empfohlen, Ihre Kontaktinformationen in die Blockchain zu registrieren. Dadurch wird sichergestellt, dass Vertragspartner wissen, wie sie Sie für Fragen zu den Verhandlungen kontaktieren können. Der Code kann lokal ausgeführt und auch über die GitHub-Seite, auf der der Code und die Website gehostet sind, überprüft werden. BitBay erhebt keine Gebühren für die Treuhandverfahren. Dieses System ist vollständig kostenlos zu verwenden. Weitere Informationen darüber, wie all dies funktioniert, finden Sie unter: "}  
};

languages['it']={
  "1": {"#it": "BitBay Mercati Decentralizzati"},
  "2": {"#it": "BitBay Mercati Decentralizzati"},
  "3": {"#it": "Collega Metamask"},
  "4": {"#it": "Non connesso"},
  "5": {"#it": "Mercati"},
  "6": {"#it": "Offerte"},
  "7": {"#it": "Contratti"},
  "8": {"#it": "Account"},
  "9": {"#it": "Informazioni"},
  "10": {"#it": "Merci"},
  "11": {"#it": "Servizi"},
  "12": {"#it": "Baratto"},
  "13": {"#it": "Trading P2P"},
  "14": {"#it": "Commodities"},
  "15": {"#it": "Mercati"},
  "16": {"#it": "Crea Contratto/Offerta"},
  "17": {"#it": "Cerca"},
  "18": {"#it": "Precedente"},
  "19": {"#it": "Successivo"},
  "20": {"#it": "Ordina: Predefinito"},
  "21": {"#it": "Ordina: Miglior prezzo"},
  "22": {"#it": "Ordina: Prezzo alto"},
  "23": {"#it": "Offerte"},
  "24": {"#it": "Contratti"},
  "25": {"#it": "Account"},
  "26": {"#it": "Si prega di collegare Metamask"},
  "27": {"#it": "Deposita token"},
  "28": {"#it": "Preleva token"},
  "29": {"#it": "Informazioni di contatto (email/signal/telegramma):"},
  "30": {"#it": "Registra informazioni di contatto al mio indirizzo (opzionale)"},
  "31": {"#it": "Elimina automaticamente i contratti completati"},
  "32": {"#it": "Aggiorna/ripristina contratti precedentemente eliminati"},
  "33": {"#it": "Le offerte private scadono: "},
  "34": {"#it": "Mai"},
  "35": {"#it": "Due settimane"},
  "36": {"#it": "Un mese"},
  "37": {"#it": "Backup dati del sito/dell'utente"},
  "38": {"#it": "Carica dati del sito/dell'utente da file"},
  "39": {"#it": "Usa l'IPFS Pinata Gateway predefinito"},
  "40": {"#it": "Informazioni"},
  "41": {"#it": "Benvenuti nel mondo dei contratti indistruttibili. Questi sono contratti di escrow a doppio deposito che coinvolgono due parti e non possono essere infranti e non richiedono arbitri di terze parti. Entrambi gli utenti versano un deposito personalizzabile insieme a un pagamento su un conto congiunto. Se l'affare va bene, entrambi lo convalidano. Se una parte cerca di truffare l'altra, l'affare alla fine scade e fallisce, in modo che nessuno vinca e il furto sia inutile. Ciò costringe gli utenti a essere onesti e a rispettare i loro accordi, poiché o vincono insieme o perdono insieme."},
  "42": {"#it": "I mercati stessi funzionano su catene Solidity come Ethereum e Polygon. Le offerte possono spaziare da merci, servizi, baratto e trading P2P. Poiché questa pagina web è completamente open source e funziona lato client, l'utente può anche scaricare questo codice da GitHub e eseguirlo localmente per una sicurezza ancora maggiore. Questo protocollo, che è stato introdotto per la prima volta da BitHalo nel 2014, precede Ethereum ed è stato il primo contratto intelligente al mondo. Questa è un'interfaccia basata sul web per mercati completamente decentralizzati."},
  "43": {"#it": "Per vendere merci, gli utenti vorranno sicuramente considerare un servizio di drop shipping o un servizio che offre sconti sullo shipping per competere con le tariffe di spedizione tipicamente trovate in grandi aziende. Per fare ciò, dovresti iscriverti a un account di spedizione di terze parti che dovrebbe consentirti di risparmiare oltre il 75% nelle spese di spedizione. I venditori possono anche addebitare ai compratori le spese di spedizione durante l'escrow, e i compratori dovrebbero fare attenzione a fare in modo che l'importo non superi i depositi o che acquistino loro stessi l'etichetta di spedizione. Gli utenti dovrebbero cercare di rimanere in comunicazione tra loro durante il processo di escrow ed è consigliabile avere un backup delle proprie chiavi in modo che entrambe le parti siano protette durante l'escrow. Sebbene questi mercati possano essere moderati attraverso l'IA (come webgpt) e la moderazione guidata dalla comunità, gli utenti sono interamente responsabili dei rischi di ciò che pubblicano e dei loro stessi escrow. Con questo in mente, è fortemente consigliato di non pubblicare contenuti illegali nel paese in cui si risiede. Per le transazioni che coinvolgono denaro contante, gli utenti dovrebbero fare la propria dovuta diligenza e il proprio 'conosci il tuo cliente' se necessario. È nell'interesse di tutti utilizzare l'escrow a doppio deposito per eliminare l'inganno nel mondo del commercio e dei servizi internazionali. È un vantaggio quando gli utenti amministrano i contratti da soli perché gli arbitri non sono in grado di conoscere la verità di una decisione che è ingiusta e possono colludere causando grandi perdite e inoltre comportano un costo maggiore. Gli utenti sono costretti a collaborare tra loro per ottenere un risultato desiderabile. Gli utenti sono anche coloro che ospitano le offerte utilizzando IPFS. Quindi è buona pratica eseguire il proprio nodo IPFS per archiviare i mercati. Si consiglia di registrare le proprie informazioni di contatto sulla blockchain. Ciò garantisce che le controparti nel contratto sappiano come contattarti per eventuali domande sulle trattative. Il codice può essere eseguito localmente e può anche essere verificato visitando la pagina GitHub dove sono ospitati il codice e il sito web. BitBay non applica alcune tariffe per gli escrow. Questo sistema è completamente gratuito da utilizzare. Per ulteriori informazioni su come funziona tutto questo, è possibile visitare: "}
};

languages['ja']={
  "1":{"#ja":"BitBay 分散型市場"},
  "2":{"#ja":"BitBay 分散型市場"},
  "3":{"#ja":"メタマスクに接続"},
  "4":{"#ja":"接続されていません"},
  "5":{"#ja":"マーケット"},
  "6":{"#ja":"オファー"},
  "7":{"#ja":"契約"},
  "8":{"#ja":"アカウント"},
  "9":{"#ja":"概要"},
  "10":{"#ja":"グッズ"},
  "11":{"#ja":"サービス"},
  "12":{"#ja":"物々交換"},
  "13":{"#ja":" P2P 取引"},
  "14":{"#ja":"商品"},
  "15":{"#ja":"市場"},
  "16":{"#ja":"契約/オファーの作成"},
  "17":{"#ja":"検索"},
  "18":{"#ja":"前へ "},
  "19":{"#ja":"次へ"},
  "20":{"#ja":"並べ替え: デフォルト"},
  "21":{"#ja":"並べ替え: 価格が安い"},
  "22":{"#ja":"並べ替え: 価格が高い"},
  "23":{"#ja" :"オファー"},
  "24":{"#ja":"契約"},
  "25":{"#ja":"アカウント"},
  "26":{"#ja":"メタマスクを接続してください"},
  "27":{"#ja":"トークンを入金"},
  "28":{"#ja":" トークンの引き出し"},
  "29":{"#ja":"連絡先情報(メール/シグナル/電報):"},
  "30":{"#ja":"連絡先の登録 私のアドレスへの情報（オプション）"},
  "31":{"#ja":"完了した契約を自動的にクリア"},
  "32":{"#ja":"更新/復元 以前にクリアされた契約"},
  "33":{"#ja":"プライベートオファーの有効期限: "},
  "34":{"#ja":"なし"},
  "35" :{"#ja":"2 週間"},
  "36":{"#ja":"1 か月"},
  "37":{"#ja" :"キャッシュされたサイト/ユーザー データをバックアップします"},
  "38":{"#ja":"サイト/ユーザー データをファイルからロードします"},
  "39":{"#ja": "デフォルトの IPFS Pinata ゲートウェイを使用する"},
  "40":{"#ja":"概要"},
  "41":{"#ja":"破られない契約の世界へようこそ 。 これらは二者間のエスクロー（二重預金）契約であり、破棄することはできず、第三者の仲裁人を必要としません。 両方のユーザーは、共同アカウントへの支払いとともにカスタマイズ可能な入金を行います。 取引がうまくいけば、両者は契約を締結します。 一方の当事者がもう一方の当事者をだまそうとすると、最終的には取引が期限切れになり、誰も得をせず、窃盗は利益を生みません。 これにより、ユーザーは、一緒に勝つか一緒に負けるかのどちらかであるため、正直になり、契約を最後まで遵守する必要があります。"},
  "42":{"#ja":"市場自体は Solidity チェーンの上で運営されています。 イーサリアムやポリゴンなど。 オファーは、商品、サービス、物々交換、P2P 取引など多岐にわたります。 この Web ページは完全にオープン ソースであり、クライアント側で実行されるため、ユーザーはこのコードを github からダウンロードしてローカルで実行して、セキュリティをさらに強化することもできます。 2014 年に BitHalo によって開発されたこのプロトコルは、イーサリアムよりも前であり、世界初のスマート コントラクトでした。 これは、完全に分散化された市場向けの Web ベースのインターフェイスです。"},
  "43":{"#ja":"商品を販売する場合、ユーザーはドロップシッピング サービスまたは割引配送を提供するサービスを必ず検討することになります。 大手企業で一般的に見られる配送料と競合するため。 これを行うには、配送料を 75% 以上節約できるサードパーティの配送アカウントにサインアップする必要があります。 売り手はエスクロー中に買い手に送料を請求することもあります。買い手は金額が保証金を超えないように注意するか、自分で配送ラベルを購入するように注意する必要があります。 ユーザーはエスクロー プロセスを通じて相互に通信を維持するように努める必要があり、エスクロー中に双方が保護されるようにキーのバックアップを作成することをお勧めします。 これらの市場は AI (webgpt など) やコミュニティ主導のモデレーションを通じてモデレートできますが、投稿内容のリスクと自分のエスクローについてはユーザーが全責任を負います。 このことを念頭に置いて、お住まいの国で違法なコンテンツを投稿しないことを強くお勧めします。 現金を伴う取引の場合、ユーザーは必要に応じて独自のデューデリジェンスを行い、「顧客を知る」必要があります。 国際商取引およびサービスの世界で詐欺行為を排除するために二重預金エスクローを使用することは、誰にとっても最大の利益になります。 仲裁人は不当な取引裁定の真実を知ることができず、共謀して多大な損失を引き起こす可能性があり、またより大きなコストも発生する可能性があるため、ユーザーが契約を自分で管理する場合にはこれが利点となります。 ユーザーは望ましい結果を達成するために互いに協力する必要があります。 ユーザーは、IPFS を使用してオファーをホストする人でもあります。 したがって、独自の IPFS ノードを実行して市場をアーカイブすることをお勧めします。 連絡先情報をブロックチェーンに登録することをお勧めします。 これにより、契約の相手方は、交渉に関する質問がある場合にあなたに連絡する方法を確実に知ることができます。 コードはローカルで実行でき、コードと Web サイトがホストされている github ページにアクセスして監査することもできます。 BitBay はエスクローに手数料をかかりません。 このシステムは完全に無料で使用できます。 これらすべてがどのように機能するかについて詳しくは、「 をご覧ください。」"}
};

languages['ko']={
  "1": {"#ko": "BitBay 탈중앙화된 시장"},
  "2": {"#ko": "BitBay 탈중앙화된 시장"},
  "3": {"#ko": "Metamask 연결"},
  "4": {"#ko": "연결되지 않음"},
  "5": {"#ko": "시장"},
  "6": {"#ko": "제안"},
  "7": {"#ko": "계약"},
  "8": {"#ko": "계정"},
  "9": {"#ko": "소개"},
  "10": {"#ko": "상품"},
  "11": {"#ko": "서비스"},
  "12": {"#ko": "물물 교환"},
  "13": {"#ko": "P2P 트레이딩"},
  "14": {"#ko": "상품"},
  "15": {"#ko": "시장"},
  "16": {"#ko": "계약/제안 생성"},
  "17": {"#ko": "검색"},
  "18": {"#ko": "이전"},
  "19": {"#ko": "다음"},
  "20": {"#ko": "정렬: 기본값"},
  "21": {"#ko": "정렬: 최저 가격"},
  "22": {"#ko": "정렬: 높은 가격"},
  "23": {"#ko": "제안"},
  "24": {"#ko": "계약"},
  "25": {"#ko": "계정"},
  "26": {"#ko": "Metamask를 연결하십시오."},
  "27": {"#ko": "토큰 입금"},
  "28": {"#ko": "토큰 출금"},
  "29": {"#ko": "연락처 정보(이메일/signal/텔레그램):"},
  "30": {"#ko": "주소에 연락처 정보 등록(선택 사항)"},
  "31": {"#ko": "자동으로 완료된 계약 지우기"},
  "32": {"#ko": "이전에 지워진 계약 새로고침/복원"},
  "33": {"#ko": "개인 제안 만료: "},
  "34": {"#ko": "안 함"},
  "35": {"#ko": "두 주"},
  "36": {"#ko": "한 달"},
  "37": {"#ko": "캐시된 사이트/사용자 데이터 백업"},
  "38": {"#ko": "파일에서 사이트/사용자 데이터 불러오기"},
  "39": {"#ko": "기본 IPFS Pinata 게이트웨이 사용"},
  "40": {"#ko": "소개"},
  "41": {"#ko": "파괴할 수 없는 계약의 세계에 오신 것을 환영합니다. 이들은 깨질 수 없는 이중 예치금 계약으로, 3자 중재인이 필요하지 않습니다. 양측 사용자는 맞춤형 예치금과 함께 공동 계정에 지불을 넣습니다. 거래가 성공하면 양측이 서명합니다. 한 쪽이 상대방을 사기하려고하면 거래는 결국 만료되어 실패하며 아무도 이기지 못하고 도난은 이익이 없게 됩니다. 이로써 사용자는 성실하고 합의를 따르도록 강제됩니다. 그들은 함께 이기거나 함께 지거나 둘 중 하나입니다."},
  "42": {"#ko": "시장 자체는 Ethereum 및 Polygon과 같은 Solidity 체인 위에서 실행됩니다. 상품, 서비스, 물물 교환 및 P2P 거래까지 제안이 다양할 수 있습니다. 이 웹페이지는 완전히 오픈 소스이며 클라이언트 측에서 실행되므로 사용자는 GitHub에서 이 코드를 다운로드하여 로컬에서 실행할 수도 있습니다. 이 프로토콜은 2014년 BitHalo에서 개척되었으며 Ethereum 이전에 세계 최초의 스마트 계약이었습니다. 이는 완전히 탈중앙화된 시장을 위한 웹 기반 인터페이스입니다."},
  "43": {"#ko": "상품을 판매하려면 사용자는 확실히 드롭 배송 서비스 또는 대기업의 배송 요금과 경쟁하기 위한 할인 배송을 제공하는 서비스를 고려해야합니다. 이를 위해 제3자 배송 계정에 등록하여 배송 비용을 75% 이상 절약할 수 있어야합니다. 판매자는 수령 중에 구매자에게 배송비를 청구할 수 있으며, 구매자는 그 금액이 예치금을 초과하지 않거나 배송 라벨을 직접 구매하는지 주의해야합니다. 사용자는 예치 중에 서로 통신하려고 노력해야하며 양측 모두가 예치 중에 보호되도록 키의 백업이 권장됩니다. 이러한 시장은 AI(예: webgpt) 및 커뮤니티 주도의 중재를 통해 관리될 수 있지만 사용자는 자신이 게시하는 내용과 자체 보증에 대한 리스크를 완전히 책임져야합니다. 이를 염두에두고 거주하는 국가에서 불법인 콘텐츠를 게시하지 않도록 강력히 권장합니다. 현금 거래에 관여하는 거래에 대해서는 사용자가 필요하면 자체 '고객 알기'를 수행해야합니다. 국제 상거래와 서비스의 속임수를 없애기 위해 이중 예치금을 사용하는 것이 모두의 이익입니다. 사용자가 계약을 스스로 관리할 때 이는 거래가 불공평하게 실패하는 것에 대한 진실을 알 수 없기 때문에 중재인이 큰 손실을 야기하고 협박 할 수 없도록 하는 장점이 있으며 또한 더 큰 비용이 발생합니다. 사용자는 원하는 결과를 얻기 위해 서로 협력해야합니다. 사용자는 또한 IPFS를 사용하여 제안을 호스팅합니다. 따라서 로컬에서 자체 IPFS 노드를 실행하여 시장을 보관하는 것이 좋은 실천입니다. 블록체인에 연락처 정보를 등록하는 것이 좋습니다. 이로써 계약 상대방이 협상에 관한 질문이 있을 경우 어떻게 연락할 지를 보장합니다. 코드는 로컬에서 실행되며 코드 및 웹사이트가 호스팅되는 GitHub 페이지를 방문하여 감사할 수도 있습니다. BitBay는 예치금에 대한 수수료를 취하지 않습니다. 이 시스템은 완전히 무료로 사용할 수 있습니다. 이 모든 것이 어떻게 작동하는지에 대한 자세한 정보는 다음을 참조하십시오: "}
}

languages['po']={
  "1": {"#po": "Mercados Descentralizados BitBay"},
  "2": {"#po": "Mercados Descentralizados BitBay"},
  "3": {"#po": "Conectar Metamask"},
  "4": {"#po": "Não conectado"},
  "5": {"#po": "Mercados"},
  "6": {"#po": "Ofertas"},
  "7": {"#po": "Contratos"},
  "8": {"#po": "Conta"},
  "9": {"#po": "Sobre"},
  "10": {"#po": "Bens"},
  "11": {"#po": "Serviços"},
  "12": {"#po": "Troca"},
  "13": {"#po": "Negociação P2P"},
  "14": {"#po": "Commodities"},
  "15": {"#po": "Mercados"},
  "16": {"#po": "Criar Contrato/Oferta"},
  "17": {"#po": "Pesquisar"},
  "18": {"#po": "Anterior"},
  "19": {"#po": "Próximo"},
  "20": {"#po": "Ordenar: Padrão"},
  "21": {"#po": "Ordenar: Melhor preço"},
  "22": {"#po": "Ordenar: Preço alto"},
  "23": {"#po": "Ofertas"},
  "24": {"#po": "Contratos"},
  "25": {"#po": "Conta"},
  "26": {"#po": "Por favor, conecte o Metamask"},
  "27": {"#po": "Depositar tokens"},
  "28": {"#po": "Retirar tokens"},
  "29": {"#po": "Informações de Contato (e-mail/signal/telegrama):"},
  "30": {"#po": "Registrar informações de contato no meu endereço (opcional)"},
  "31": {"#po": "Limpar automaticamente contratos concluídos"},
  "32": {"#po": "Atualizar/restaurar contratos previamente limpos"},
  "33": {"#po": "Ofertas privadas expiram: "},
  "34": {"#po": "Nunca"},
  "35": {"#po": "Duas semanas"},
  "36": {"#po": "Um mês"},
  "37": {"#po": "Backup de dados do site/usuário"},
  "38": {"#po": "Carregar dados do site/usuário do arquivo"},
  "39": {"#po": "Usar o IPFS Pinata Gateway padrão"},
  "40": {"#po": "Sobre"},
  "41": {"#po": "Bem-vindo ao mundo dos contratos inquebráveis. Esses são contratos de garantia de duas partes (depósito duplo) que não podem ser quebrados e não requerem árbitros de terceiros. Ambos os usuários depositam um valor personalizável juntamente com um pagamento em uma conta conjunta. Se o negócio correr bem, ambos concordam com isso. Se uma das partes tentar fraudar a outra, o acordo eventualmente expira e se desfaz, de modo que ninguém ganha e o roubo não é lucrativo. Isso força os usuários a serem honestos e a cumprir seus acordos, pois ou ganham juntos ou perdem juntos."},
  "42": {"#po": "Os próprios mercados funcionam em cima de blockchains Solidity, como Ethereum e Polygon. As ofertas podem variar de bens, serviços, trocas e negociações P2P. Como esta página da web é totalmente de código aberto e funciona no lado do cliente, o usuário também pode baixar este código do GitHub e executá-lo localmente para uma segurança ainda maior. Esse protocolo, que foi pioneiro pela BitHalo em 2014, antecede o Ethereum e foi o primeiro contrato inteligente do mundo. Esta é uma interface baseada na web para mercados totalmente descentralizados."},
  "43": {"#po": "Para vender bens, os usuários definitivamente devem considerar um serviço de drop shipping ou um serviço que ofereça descontos no envio para competir com as tarifas de envio geralmente encontradas em grandes empresas. Para fazer isso, você deve se inscrever em uma conta de envio de terceiros que deve permitir que você economize mais de 75% no envio. Os vendedores também podem cobrar dos compradores pelo envio durante o escrow, e os compradores devem ter cuidado para garantir que o valor não ultrapasse os depósitos ou que comprem eles mesmos o rótulo de envio. Os usuários devem tentar se manter em comunicação durante o processo de escrow, e é recomendável ter um backup de suas chaves para que ambas as partes estejam protegidas durante o escrow. Embora esses mercados possam ser moderados por meio de IA (como o webgpt) e moderação impulsionada pela comunidade, os usuários são totalmente responsáveis pelos riscos do que postam e por seus próprios escrows. Com isso em mente, é altamente recomendável não postar conteúdo ilegal no país em que reside. Para negócios que envolvem dinheiro, os usuários devem fazer sua própria diligência e seu próprio \"conheça o seu cliente\", se necessário. É do interesse de todos usar o escrow de depósito duplo para se livrar do engano no mundo do comércio e serviços internacionais. É uma vantagem quando os usuários administram os contratos sozinhos, pois os árbitros não conseguem conhecer a verdade de uma decisão injusta e podem conluio causando grandes perdas, além de incorrer em um custo maior. Os usuários são forçados a trabalhar juntos para alcançar um resultado desejável. Os usuários também são aqueles que hospedam as ofertas usando o IPFS. Portanto, é uma boa prática executar seu próprio nó IPFS para arquivar os mercados. Recomenda-se que você registre suas informações de contato na blockchain. Isso garante que as contrapartes no contrato saibam como entrar em contato com você para quaisquer dúvidas sobre as negociações. O código pode ser executado localmente e também pode ser auditado visitando a página do GitHub onde o código e o site estão hospedados. O BitBay não cobra nenhuma taxa pelos escrows. Este sistema é totalmente gratuito para usar. Para obter mais informações sobre como tudo isso funciona, você pode visitar: "}  
};

languages['ru'] = {
  "1": {"#ru": "Децентрализованные рынки BitBay"},
  "2": {"#ru": "Децентрализованные рынки BitBay"},
  "3": {"#ru": "Подключить Metamask"},
  "4": {"#ru": "Не подключено"},
  "5": {"#ru": "Рынки"},
  "6": {"#ru": "Предложения"},
  "7": {"#ru": "Контракты"},
  "8": {"#ru": "Аккаунт"},
  "9": {"#ru": "О нас"},
  "10": {"#ru": "Товары"},
  "11": {"#ru": "Услуги"},
  "12": {"#ru": "Бартер"},
  "13": {"#ru": "P2P Торговля"},
  "14": {"#ru": "Товары"},
  "15": {"#ru": "Рынки"},
  "16": {"#ru": "Создать Контракт/Предложение"},
  "17": {"#ru": "Поиск"},
  "18": {"#ru": "Предыдущий"},
  "19": {"#ru": "Следующий"},
  "20": {"#ru": "Сортировать: По умолчанию"},
  "21": {"#ru": "Сортировать: Лучшая цена"},
  "22": {"#ru": "Сортировать: Высокая цена"},
  "23": {"#ru": "Предложения"},
  "24": {"#ru": "Контракты"},
  "25": {"#ru": "Аккаунт"},
  "26": {"#ru": "Пожалуйста, подключите Metamask"},
  "27": {"#ru": "Депозит токенов"},
  "28": {"#ru": "Вывести токены"},
  "29": {"#ru": "Контактная информация (электронная почта/signal/телеграм):"},
  "30": {"#ru": "Зарегистрировать контактную информацию по моему адресу (по желанию)"},
  "31": {"#ru": "Автоматически очищать завершенные контракты"},
  "32": {"#ru": "Обновить/восстановить ранее очищенные контракты"},
  "33": {"#ru": "Срок действия частных предложений: "},
  "34": {"#ru": "Никогда"},
  "35": {"#ru": "Две недели"},
  "36": {"#ru": "Один месяц"},
  "37": {"#ru": "Резервное копирование кэша сайта/пользовательских данных"},
  "38": {"#ru": "Загрузить данные сайта/пользователя из файла"},
  "39": {"#ru": "Использовать стандартный IPFS Pinata Gateway"},
  "40": {"#ru": "О нас"},
  "41": {"#ru": "Добро пожаловать в мир нерушимых контрактов. Это двусторонние эскроу-контракты (двойной депозит), которые нельзя нарушить и не требуют арбитров от третьих лиц. Оба пользователи размещают настраиваемый депозит вместе с оплатой на общий счет. Если сделка проходит успешно, они оба ее подтверждают. Если одна из сторон пытается обмануть другую, сделка в конечном итоге истекает и разрушается, так что никто не выигрывает, и кража становится бесполезной. Это заставляет пользователей быть честными и соблюдать свои соглашения, поскольку они либо выигрывают вместе, либо проигрывают вместе."},
  "42": {"#ru": "Сами рынки работают на блокчейнах Solidity, таких как Ethereum и Polygon. Предложения могут варьироваться от товаров, услуг, бартера до P2P-торговли. Поскольку эта веб-страница полностью открытого исходного кода и работает на стороне клиента, пользователь также может загрузить этот код с GitHub и запустить его локально для еще большей безопасности. Этот протокол, который был создан BitHalo еще в 2014 году, предшествовал Ethereum и был первым в мире смарт-контрактом. Это веб-интерфейс для полностью децентрализованных рынков."},
  "43": {"#ru": "Для продажи товаров пользователям определенно следует рассмотреть услугу по доставке или сервис, предоставляющий скидки на доставку для конкуренции с тарифами на доставку, обычно предлагаемыми крупными компаниями. Для этого вы должны зарегистрироваться в учетной записи доставки от третьих лиц, которая должна позволять вам сэкономить более 75% на доставке. Продавцы также могут взимать плату за доставку у покупателей во время эскроу, и покупателям следует быть осторожными, чтобы убедиться, что сумма не превышает депозиты, или они сами покупают этикетку на доставку. Пользователям следует стараться поддерживать связь друг с другом в процессе эскроу, и рекомендуется иметь резервные ключи, чтобы обе стороны были защищены во время эскроу. Хотя эти рынки могут быть модерированы через ИИ (например, webgpt) и модерацию, осуществляемую сообществом, пользователи полностью несут ответственность за риски того, что они публикуют, и за свои собственные эскроу. Имея в виду это, настоятельно рекомендуется не публиковать контент, который является незаконным в стране вашего проживания. Для сделок, которые включают наличные деньги, пользователи должны проводить свою собственную дополнительную проверку и свою собственную \"проверку клиента\", если это необходимо. Это в интересах всех использовать двойной депозитный эскроу для устранения обмана в мире международной торговли и услуг. Преимущество заключается в том, что пользователи сами администрируют контракты, поскольку арбитры не могут узнать правду сделки, вынося неравные решения и могут сговариваться, что приводит к большим потерям, а также они несут большие затраты. Пользователей вынуждают работать друг с другом для достижения желаемого результата. Пользователи также сами размещают предложения с использованием IPFS. Поэтому рекомендуется запускать свой собственный узел IPFS для архивации рынков. Рекомендуется зарегистрировать свою контактную информацию в блокчейне. Это гарантирует, что контрагенты в контракте знают, как связаться с вами для любых вопросов по поводу переговоров. Код может быть запущен локально и также может быть проверен, посетив страницу GitHub, где размещены код и сайт. BitBay не взимает никаких сборов за эскроу. Эта система полностью бесплатна в использовании. Дополнительную информацию о том, как все это работает, вы можете узнать по адресу: "}
}

languages['sp'] = {
  "1": {"#sp": "Mercados Descentralizados BitBay"},
  "2": {"#sp": "Mercados Descentralizados BitBay"},
  "3": {"#sp": "Conectar Metamask"},
  "4": {"#sp": "No conectado"},
  "5": {"#sp": "Mercados"},
  "6": {"#sp": "Ofertas"},
  "7": {"#sp": "Contratos"},
  "8": {"#sp": "Cuenta"},
  "9": {"#sp": "Acerca de nosotros"},
  "10": {"#sp": "Bienes"},
  "11": {"#sp": "Servicios"},
  "12": {"#sp": "Trueque"},
  "13": {"#sp": "Trading P2P"},
  "14": {"#sp": "Productos"},
  "15": {"#sp": "Mercados"},
  "16": {"#sp": "Crear Contrato/Oferta"},
  "17": {"#sp": "Buscar"},
  "18": {"#sp": "Anterior"},
  "19": {"#sp": "Siguiente"},
  "20": {"#sp": "Ordenar: Por defecto"},
  "21": {"#sp": "Ordenar: Mejor precio"},
  "22": {"#sp": "Ordenar: Precio alto"},
  "23": {"#sp": "Ofertas"},
  "24": {"#sp": "Contratos"},
  "25": {"#sp": "Cuenta"},
  "26": {"#sp": "Por favor, conecte Metamask"},
  "27": {"#sp": "Depositar tokens"},
  "28": {"#sp": "Retirar tokens"},
  "29": {"#sp": "Información de contacto (correo electrónico/signal/telegrama):"},
  "30": {"#sp": "Registrar información de contacto en mi dirección (opcional)"},
  "31": {"#sp": "Borrar automáticamente contratos completados"},
  "32": {"#sp": "Actualizar/restaurar contratos previamente borrados"},
  "33": {"#sp": "Vencimiento de ofertas privadas: "},
  "34": {"#sp": "Nunca"},
  "35": {"#sp": "Dos semanas"},
  "36": {"#sp": "Un mes"},
  "37": {"#sp": "Copia de seguridad de datos del sitio/usuario"},
  "38": {"#sp": "Cargar datos del sitio/usuario desde archivo"},
  "39": {"#sp": "Usar la puerta de enlace IPFS Pinata predeterminada"},
  "40": {"#sp": "Acerca de nosotros"},
  "41": {"#sp": "Bienvenido al mundo de los contratos irrompibles. Estos son contratos de custodia entre dos partes (doble depósito) que no pueden romperse y no requieren árbitros de terceros. Ambos usuarios colocan un depósito personalizable junto con un pago en una cuenta conjunta. Si el trato va bien, ambos lo confirman. Si una de las partes intenta estafar a la otra, el trato eventualmente expirará y fracasará, de modo que nadie gana y el robo no es rentable. Esto obliga a los usuarios a ser honestos y cumplir con sus acuerdos, ya que o ganan juntos o pierden juntos."},
  "42": {"#sp": "Los propios mercados se ejecutan en cadenas Solidity como Ethereum y Polygon. Las ofertas pueden variar desde bienes, servicios, trueque hasta trading P2P. Dado que esta página web es de código abierto y se ejecuta en el lado del cliente, el usuario también puede descargar este código desde GitHub y ejecutarlo localmente para una mayor seguridad. Este protocolo, que fue pionero de BitHalo en 2014, precedió a Ethereum y fue el primer contrato inteligente del mundo. Esta es una interfaz web para mercados totalmente descentralizados."},
  "43": {"#sp": "Para vender bienes, los usuarios definitivamente deberían considerar un servicio de envío directo o un servicio que ofrezca envíos con descuento para competir con las tarifas de envío que se encuentran comúnmente en las principales empresas. \
    Para hacer esto, debería registrarse en una cuenta de envío de terceros que le permita ahorrar más del 75% en envíos. Los vendedores también pueden cobrar a los compradores por el envío mientras está en custodia, y los compradores deben tener cuidado de asegurarse de que la cantidad no supere los depósitos o que compren la etiqueta de envío ellos mismos. \
    Se recomienda a los usuarios que mantengan la comunicación entre ellos durante el proceso de custodia y que tengan una copia de seguridad de sus claves para que ambas partes estén protegidas durante la custodia. \
    Aunque estos mercados podrían ser moderados a través de la IA (como webgpt) y la moderación impulsada por la comunidad, los usuarios son totalmente responsables de los riesgos de lo que publican y de sus propias custodias. \
    Con eso en mente, se recomienda encarecidamente no publicar contenido que sea ilegal en el país en el que reside. \
    Para acuerdos que involucren efectivo, los usuarios deben realizar su propia diligencia debida y su propio \"conocimiento del cliente\" si es necesario. \
    Es del interés de todos utilizar la custodia de doble depósito para eliminar el engaño en el mundo del comercio y los servicios internacionales. \
    Es una ventaja cuando los usuarios administran los contratos ellos mismos porque los árbitros no pueden conocer la verdad de un trato que falla injustamente y pueden coludirse causando grandes pérdidas, además de incurrir en un mayor costo. \
    Los usuarios están obligados a trabajar entre ellos para lograr un resultado deseable. \
    Los usuarios también son quienes alojan las ofertas utilizando IPFS. \
    Por lo tanto, es una buena práctica ejecutar su propio nodo IPFS para archivar los mercados. \
    Se recomienda que registre su información de contacto en la cadena de bloques. Esto garantiza que las contrapartes en el contrato sepan cómo comunicarse con usted para cualquier pregunta sobre las negociaciones. \
    El código se puede ejecutar localmente y también se puede auditar visitando la página de GitHub donde se aloja el código y el sitio web. \
    BitBay no cobra tarifas por las custodias. Este sistema es completamente gratuito de usar. \
    Para obtener más información sobre cómo funciona todo esto, puede visitar: "
  }
};
